### ISSUE TITLE
Swar stuck on tranferring to a full drive

### ISSUE THREAD

**Issue by terragnosis777** [swar/Swar-Chia-Plot-Manager#1107]
I thought that SWAR would be able to detect that a drive was not a candidate for a plot file when it was full, but I have a job at almost 24 hours now stuck on Phase 5 transferring to that drive. What can I do to save the job and prevent this?

![190180136_10157603177961706_2961884594663431854_n](https://user-images.githubusercontent.com/85305690/120684099-2c548b80-c453-11eb-8996-7edf12cc8ad4.jpg)

**Comment by creamsoup** [comment]
you can just copy the final file (look at the log) and rename to something.plot.
btw, it is not swar. it is chia-blockchain causes this. although i can't think better behavior than this.

**Comment by terragnosis777** [comment]
Thanks for getting back. I managed this by moving an already completed file off of the full drive, then removing that drive from the list in the SWAR config file, then resetting the plot manager. It completed the transfer and that's all. It's only a problem I'll have a few times, but I'll probably wait until one is close (within 2-3 plots), remove it from the list, then just copy some over to fill it up. That way there will be no bottleneck going forward.
