### ISSUE TITLE
No error, but no work

### ISSUE THREAD

**Issue by niu12503** [swar/Swar-Chia-Plot-Manager#1117]
![QQ截图20210604093203](https://user-images.githubusercontent.com/21340487/120732395-d1d13300-c517-11eb-998d-7f7062298ce1.jpg)

**Comment by creamsoup** [comment]
no debug info

what's your config? any logs in `debug.log`?

**Comment by Arash-93** [comment]
I have the same problem, who knows how to fix?

**Comment by niu12503** [comment]
I solve the problem: check farmer_ public_ Key and pool_ public_ key:

**Comment by Arash-93** [comment]
Could you please explain more

**Comment by niu12503** [comment]
I add farmer again_ public_ Key and pool_ public_ Key:，It works right
Maybe the key was wrong   Or the format is wrong

**Comment by Arash-93** [comment]
I tried it didn't work for me
