### ISSUE TITLE
Check remaining space on destination is sufficient

### ISSUE THREAD

**Issue by inan0812** [swar/Swar-Chia-Plot-Manager#12]
Noticed the manager start up a plot despite one of the destination drives only having about 70gb of free space.

The code should check if there is sufficient space before plotting, and if not, skip to the next available drive listed in the config.

**Comment by thatramenpanda** [comment]
+1

**Comment by lpenrod** [comment]
+1

**Comment by EliveltonRepolho** [comment]
+1
