### ISSUE TITLE
(new feature) web ui

### ISSUE THREAD

**Issue by daryledesilva** [swar/Swar-Chia-Plot-Manager#120]
hello I'd like to suggest a feature to add web ui similar to what eth t-rex miner is doing. I'm a web developer so i can help with the webpage part, I'm just not too knowledgeable with python. but if we can come up with a way to open up ports then provide a json data, i can help you with this. let me know if you're interested then we can have a more detailed discussion😁

**Comment by swar** [comment]
@daryledesilva Yes I would like this as well. However with Python you would have to come up with it via Flask or Django, with Django requiring way more headroom to get it working. I would be open to help on it :)

**Comment by daryledesilva** [comment]
i see. okay that's completely new to me. I'll read about it first then play around with my fork. if i have something good to show next time, ill let you know. for the meanwhile i saw the prometheus PR and that looks similar to what im suggesting though not 💯% the same (and it requires some 3rd party stuff instead of everything native to this package) anwyay I'll play around with that too. closing this issue for now. cheers

**Comment by lorado** [comment]
Isn't `view` command reading logs every time and analyses it? Theoretically web UI could be written as a separate package. 
I think this should also work in some way, that you have Web UI (PWA running somewhere, maybe even global in the inet), where you can add your servers (with ip and so), so web ui is collecting information from a different harvester servers.

So similar like chia dashboard from foxypool works: https://docs.foxypool.io/chia-dashboard-satellite/
You have to setup so called satellite on you harvesters, which are the sending the information to a one place.
