### ISSUE TITLE
the system does not reach the path

### ISSUE THREAD

**Issue by SilantevDenis** [swar/Swar-Chia-Plot-Manager#1223]
![swar-error](https://user-images.githubusercontent.com/18242419/124251506-a8afbc80-db2e-11eb-9d3d-7bf02d3ffea0.png)

My OS windows 10 64bit. Python version 3.9.6. 

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6753528/config.txt)

**Comment by swar** [comment]
Change the log file location to a valid location
