### ISSUE TITLE
is there a way to get swar updated for 1.2

### ISSUE THREAD

**Issue by madjin-zz** [swar/Swar-Chia-Plot-Manager#1233]
Have problems with Madmax not using my entire IO on phase 2 3 or 4

**Comment by sxwailyc** [comment]
i had fork and add support for add -c param[pool_contract_address]

https://github.com/sxwailyc/Swar-Chia-Plot-Manager.git

**Comment by jack60612** [comment]
@madjin-zz my fork was introduced into the code just update swar to the latest version

**Comment by jack60612** [comment]
Please close this issue

**Comment by mleen** [comment]
> i had fork and add support for add -c param[pool_contract_address]
> 
> https://github.com/sxwailyc/Swar-Chia-Plot-Manager.git

it cann't work
win10

**Comment by swar** [comment]
Should be working
