### ISSUE TITLE
Issue with Pool Protocol

### ISSUE THREAD

**Issue by racabu** [swar/Swar-Chia-Plot-Manager#1237]
Upgraded to the latest version, added the following to the job file:
    pool_contract_address: https://na1.pool.space

The manager starts correctly, but does not show anything under the viewer... looks like nothing is plotting either.

**Comment by racabu** [comment]
https://imgur.com/a/Frhyp9B

**Comment by nighty2k7** [comment]
Same. Pulled the current source as zip, added (self_pooling) pool_contract_address: MYLAUNCHERID. Does not seem to start to work

**Comment by UnclMunkeh** [comment]
I think the address is supposed to be the Pool Contract Address (if you create a pool plot in the GUI and look at the log, you'll see it).

That said, I have the same problem using the contract address.

**Comment by icey35** [comment]
I downloaded the latest files a few hours ago.  I added a pool contract but am getting the following in my log files:

  File "chia\util\bech32m.py", line 116, in decode_puzzle_hash
ValueError: Invalid Address
[10604] Failed to execute script chia

the manager can see plots being run by the gui client but seems to error out when trying to start its own

I also had the manager restarting due to stale psutil error which i never got before, but running cmd as administrator seemed to fix it.

**Comment by icey35** [comment]
the pool contract key is the only one defined in config.yaml, all other keys i am letting it defer to the chia client defaults

**Comment by UnclMunkeh** [comment]
I'm seeing the same thing.

**Comment by UnclMunkeh** [comment]
After becoming a bit more un-dumb, I scratch wrote the config file and it looks to be working now.  

Maybe it was an aberrant space or something.

**Comment by icey35** [comment]
interesting, im gonna try to re-use my (working) 117 config with just the pool contract line inserted and see what happens

**Comment by racabu** [comment]
Worked for me when changing the contract address to the one mentioned above. I was able to get it from the Chia Gui.

**Comment by icey35** [comment]
ok just to clarify for everyone who might find this thread later - 
your 'pool_contract_address' in the config file is the value that shows up in the 'plots' section of the GUI when make a pool plot, the value between "node id" and "filename"

it is NOT the launcher id from your NFT plot in the 'pool' tab on the GUI

plot a pool portable plot in the gui first, and then find the value to paste into your swar config and youll be set
