### ISSUE TITLE
pool_contract_address isn't working, flag -c isn't working. (Madmax)

### ISSUE THREAD

**Issue by Trypt88** [swar/Swar-Chia-Plot-Manager#1241]
Trying to use Swar + MadMax + Pool Protocol... failed.
Got this in the log file.

Multi-threaded pipelined Chia k32 plotter - 82f92a9
Build 0.1.1 for Windows. Check for latest updates: https://stotiks.github.io/chia-plotter/

Pool Public Key (for solo farming) or Pool Contract Address (for pool farming) needs to be specified via -p or -c, see `chia_plot --help`.

**Comment by kata32** [comment]
Yes me too
[https://github.com/swar/Swar-Chia-Plot-Manager/commit/826c3bae2afbbb9788bf46b8e4f1919288a0bed4#r53394466](url)

**Comment by kata32** [comment]
[missing in plot.py](https://github.com/swar/Swar-Chia-Plot-Manager/commit/826c3bae2afbbb9788bf46b8e4f1919288a0bed4#r53394466)

**Comment by swar** [comment]
@kata32  good catch. I added it to MadMax and lets see if that works.

@Trypt88  when you get a chance can you try again

**Comment by CityJumperAC** [comment]
I tested it this way, and it works!
