### ISSUE TITLE
SWAR with MADMAX , plots not starting

### ISSUE THREAD

**Issue by igkovace** [swar/Swar-Chia-Plot-Manager#1252]
Hi,

I have setup to run SWAR with madmax, but for some reason when I start SWAR, Manager status is RUNNING but plots are not generating? Does someone has this problem. Thx. (Config file attached)
[config.zip](https://github.com/swar/Swar-Chia-Plot-Manager/files/6830047/config.zip)

**Comment by berejznoy** [comment]
See the log file D:\#PRIVATNO#\Swar-Chia-Plot-Manager-main\Log. I have some problem

**Comment by igkovace** [comment]
I don't have any logs generated in ....\Log folder :(.

**Comment by igkovace** [comment]
I find what was the problem at the end, with chia you dont need '\' at the end for temporary & destination directory ('X:\temp'), but for madmax plotting you need it ('X:\temp\')
