### ISSUE TITLE
[Bug] farmer_public_key and pool_public_key in plot command been changed

### ISSUE THREAD

**Issue by hanuxxx** [swar/Swar-Chia-Plot-Manager#136]
config.yaml

>   \- name: D
    max_plots: 999
    farmer_public_key: 0xa3becd0f1c10012a769295002d7ce52ea36a85bf5fd6d3d4918a55d58486dcf4330288a980141cac99895348fd4ee7d4
    pool_public_key: 0x8fc0a6b25b804eaf2108aa90246bcf8e9ed53ffdd85dd5b73bf8ff90d200d38b431b3c6b00f851f0e8e8b01efe3b6482
    temporary_directory: D:\cache\Chia
    temporary2_directory:
    destination_directory: H:\Chia2
    size: 32
    bitfield: true
    threads: 2
    buckets: 64
    memory_buffer: 8000
    max_concurrent: 1
    max_concurrent_with_start_early: 2
    stagger_minutes: 60
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

manager.log
> 2021-05-07 11:56:37 [INFO]: Starting with plot command: ['C:\\Users\\shm22\\AppData\\Local\\chia-blockchain\\app-1.1.4\\resources\\app.asar.unpacked\\daemon\\chia.exe', 'plots', 'create', '-k', '32', '-b', '8000', '-t', 'D:\\cache\\Chia', '-d', 'H:\\Chia2', '-r', '2', '-u', '64', '-f', '25202710833931698181115152245530650964865974003882205692489579147028350259242819351608153610701447009453492788979668', '-p', '22125541458114512442558759180711115368236810329104808097304845010578666467810826519674336975019786331858157210133634']

D_2021-05-07_11_56_37_158861.log
> [9276] Failed to execute script chia
Traceback (most recent call last):
  File "chia\cmds\chia.py", line 81, in <module>
  File "chia\cmds\chia.py", line 77, in main
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "chia\cmds\plots.py", line 135, in create_cmd
  File "chia\plotting\create_plots.py", line 55, in create_plots
ValueError: Length of bytes object not equal to G1Element::SIZE

**Comment by nvkosykh** [comment]
delete ppk and fpk from config, in manager bug, this string put in integer in start command
