### ISSUE TITLE
details for the completed plots 

### ISSUE THREAD

**Issue by shafran666** [swar/Swar-Chia-Plot-Manager#141]
Hi
It would be good idea in my opinion to add details  (mostly times for phases and time for the whole plot) for completed plots. It would be easier for testing and tweaking the config for a hardware

**Comment by Neosettler** [comment]
Copied destination/time would be nice and feedback if something went wrong.

**Comment by swar** [comment]
Honestly, if someone wants to make a PR with some of this info then I can review. 

But I have much more pressing items to add than adding in more logging after a plot is completed.
