### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by lakymoon** [swar/Swar-Chia-Plot-Manager#142]
PS D:\Swar-Chia-Plot-Manager-main> python .\manager.py start
Traceback (most recent call last):
  File "D:\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "D:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "D:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 102, in get_config_info
    config = _get_config()
  File "D:\Swar-Chia-Plot-Manager-main\plotmanager\library\parse\configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\ShopComputer\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "D:\Swar-Chia-Plot-Manager-main\config.yaml", line 9, column 8

Thanks

**Comment by Amneamnius** [comment]
Can you attach your config.yalm? Looks like a value is not properly set

**Comment by lakymoon** [comment]
# This is a single variable that should contain the location of your chia executable file. This is the blockchain executable.
#
# WINDOWS EXAMPLE: C:\Users\Swar\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia.exe
#   LINUX EXAMPLE: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia
#  LINUX2 EXAMPLE: /home/swar/chia-blockchain/venv/bin/chia
chia_location: C:\Users\ShopComputer\AppData\Local\chia-blockchain\app-1.1.4\resources\app.asar.unpacked\daemon\chia.exe


manager:
  # These are the config settings that will only be used by the plot manager.
  #
  # check_interval: The number of seconds to wait before checking to see if a new job should start.
  #      log_level: Keep this on ERROR to only record when there are errors. Change this to INFO in order to see more
  #                 detailed logging. Warning: INFO will write a lot of information.
  check_interval: 60
  log_level: INFO


log:
  # folder_path: This is the folder where your log files for plots will be saved.
  folder_path: D:\Swar-Chia-Plot-Manager-main\Logs


view:
  # These are the settings that will be used by the view.
  #
  #            check_interval: The number of seconds to wait before updating the view.
  #           datetime_format: The datetime format that you want displayed in the view. See here
  #                            for formatting: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
  # include_seconds_for_phase: This dictates whether seconds are included in the phase times.
  #        include_drive_info: This dictates whether the drive information will be showed.
  #               include_cpu: This dictates whether the CPU information will be showed.
  #               include_ram: This dictates whether the RAM information will be showed.
  #        include_plot_stats: This dictates whether the plot stats will be showed.
  check_interval: 60
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true


notifications:
  # These are different settings in order to notified when the plot manager starts and when a plot has been completed.

  # DISCORD
  notify_discord: false
  discord_webhook_url: https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  # PLAY AUDIO SOUND
  notify_sound: false
  song: audio.mp3

  # PUSHOVER PUSH SERVICE
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  
  # TWILIO
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890


progress:
  # phase_line_end: These are the settings that will be used to dictate when a phase ends in the progress bar. It is
  #                 supposed to reflect the line at which the phase will end so the progress calculations can use that
  #                 information with the existing log file to calculate a progress percent.
  #   phase_weight: These are the weight to assign to each phase in the progress calculations. Typically, Phase 1 and 3
  #                 are the longest phases so they will hold more weight than the others.
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88


global:
  # These are the settings that will be used globally by the plot manager.
  #
  # max_concurrent: The maximum number of plots that your system can run. The manager will not kick off more than this
  #                 number of plots total over time.
  max_concurrent: 10


jobs:
  # These are the settings that will be used by each job. Please note you can have multiple jobs and each job should be
  # in YAML format in order for it to be interpreted correctly. Almost all the values here will be passed into the
  # Chia executable file.
  #
  # Check for more details on the Chia CLI here: https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference
  #
  # name: This is the name that you want to give to the job.
  # max_plots: This is the maximum number of jobs to make in one run of the manager. Any restarts to manager will reset
  #            this variable. It is only here to help with short term plotting.
  #
  # [OPTIONAL] farmer_public_key: Your farmer public key. If none is provided, it will not pass in this variable to the
  #                               chia executable which results in your default keys being used. This is only needed if
  #                               you have chia set up on a machine that does not have your credentials.
  # [OPTIONAL] pool_public_key: Your pool public key. Same information as the above.
  #
  # temporary_directory: Only a single directory should be passed into here. This is where the plotting will take place.
  # [OPTIONAL] temporary2_directory: Can be a single value or a list of values. This is an optional parameter to use in
  #                                  case you want to use the temporary2 directory functionality of Chia plotting.
  # destination_directory: Can be a single value or a list of values. This is the final directory where the plot will be
  #                        transferred once it is completed. If you provide a list, it will cycle through each drive
  #                        one by one.
  #
  # size: This refers to the k size of the plot. You would type in something like 32, 33, 34, 35... in here.
  # bitfield: This refers to whether you want to use bitfield or not in your plotting. Typically, you want to keep
  #           this as true.
  # threads: This is the number of threads that will be assigned to the plotter. Only phase 1 uses more than 1 thread.
  # buckets: The number of buckets to use. The default provided by Chia is 128.
  # memory_buffer: The amount of memory you want to allocate to the process.
  # max_concurrent: The maximum number of plots to have for this job at any given time.
  # max_concurrent_with_start_early: The maximum number of plots to have for this job at any given time including
  #                                  phases that started early.
  # stagger_minutes: The amount of minutes to wait before the next job can get kicked off. You can even set this to
  #                  zero if you want your plots to get kicked off immediately when the concurrent limits allow for it.
  # max_for_phase_1: The maximum number of plots on phase 1 for this job.
  # concurrency_start_early_phase: The phase in which you want to start a plot early. It is recommended to use 4 for
  #                                this field.
  # concurrency_start_early_phase_delay: The maximum number of seconds to wait before a new plot gets kicked off when
  #                                      the start early phase has been detected.
  # temporary2_destination_sync: This field will always submit the destination directory as the temporary2 directory.
  #                              These two directories will be in sync so that they will always be submitted as the
  #                              same value.
  - name: micron
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: O:\
    temporary2_directory:
    destination_directory: Q:\Plots
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 3390
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 20
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by lakymoon** [comment]
[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6444971/config.txt)


Thanks ^-^

**Comment by Amneamnius** [comment]
Weird there's no extra spaces that I can see that might mess with things. Maybe try changing log_level back to ERROR, or maybe O:\tempPlots instead of just O:\?

**Comment by Cminer3207** [comment]
You must check all inputs to ensure there is ONE space, and ONE space only after entries. 

Example
chia_location: C:\Users\    CORRECT
chia_location:C:\Users\     INCORRECT

**Comment by swar** [comment]
@Cminer3207  has the correct solution.

**Comment by lakymoon** [comment]
First of all, Sorry for my poor English.   | ..|

I am Chinese ha 😊

 

And thanks a lot . I have not login to Github for several days. 

Receiving these  reply, such a kind man you are.

 

 

And, may I, another question?  ^-^

       My motherboard is 

              C8H

       My cpu is: 

5950X 

And I have 3  SSD driver:

       PM983 1.8T

       PM983 1.8T

       Samsung 970EVO 2T

Maybe, you know the better strategy  🤭

 

 

Thanks again.

 

发件人: ***@***.*** ***@***.***> 代表 Swar Patel
发送时间: 2021-05-14 0:39
收件人: swar/Swar-Chia-Plot-Manager ***@***.***>
抄送: Minions ***@***.***>; Author ***@***.***>
主题: Re: [swar/Swar-Chia-Plot-Manager] Start error (#142)

 

@Cminer3207 <https://github.com/Cminer3207>  has the correct solution.

**Comment by Cminer3207** [comment]
You should post this under its own Thread. 
You should also include RAM amount.

**Comment by Cminer3207** [comment]
I think 3 jobs running. 
Each job uses an nvme drive...

temporary_directory: 
threads: 2
Memory_buffer: 8000
max_concurrent: 10
max_for_phase_1: 3

the Samsung EVO will plot faster... 
Assign your destination_drive and 
max_for_phase_1: 4

**Comment by lakymoon** [comment]
My Ram is 128GB,

 

Thanks a lot, I will try this today.

 

😊

 

发件人: ***@***.*** ***@***.***> 代表 Cminer3207
发送时间: 2021-05-14 10:17
收件人: swar/Swar-Chia-Plot-Manager ***@***.***>
抄送: Minions ***@***.***>; Author ***@***.***>
主题: Re: [swar/Swar-Chia-Plot-Manager] Start error (#142)

 

I think 3 jobs running.
Each job uses an nvme drive...

temporary_directory:
threads: 2
Memory_buffer: 8000
max_concurrent: 10
max_for_phase_1: 3

the Samsung EVO will plot faster...
Assign your destination_drive and
max_for_phase_1: 4

**Comment by Cminer3207** [comment]
Thank you. 
Your Samsung EVO is fast(write speed of 7000) but has a very short lifespan of 1200 TB Written (4600 plots).

Your PM983 is slow (write speed of 1900)... but lives for 5800TB W (22,000 Plots). 

Consider using the Firecuda520 2TB for your next build. 
It lands in between... Write speed of 5000, with a lifespan of 3600TB (14,000 Plots).

**Comment by lakymoon** [comment]
Sorry to bother you again. /(ㄒoㄒ)/~~

To my system, what’s the best values for the properties below:

1. stagger_minutes 

       2. max_concurrent_with_start_early:

       3. concurrency_start_early_phase: 

       4. concurrency_start_early_phase_delay: 

 

Thanks a lot.😊

 

 

发件人: ***@***.*** ***@***.***> 代表 Cminer3207
发送时间: 2021-05-14 11:06
收件人: swar/Swar-Chia-Plot-Manager ***@***.***>
抄送: Minions ***@***.***>; Author ***@***.***>
主题: Re: [swar/Swar-Chia-Plot-Manager] Start error (#142)

 

Thank you.
Your Samsung EVO is fast(write speed of 7000) but has a very short lifespan of 1200 TB Written (4600 plots).

Your PM983 is slow (write speed of 1900)... but lives for 5800TB W (22,000 Plots).

Consider using the Firecuda520 2TB for your next build.
It lands in between... Write speed of 5000, with a lifespan of 3600TB (14,000 Plots).

**Comment by Cminer3207** [comment]
Stagger depends on your CPU... but probably 60. 

stagger_minutes: 60
max_concurrency_with_start_early: 10
concurrency_start_early_phase: 4
concurrency_start_early_phase_delay_: 0

**Comment by lakymoon** [comment]
Thanks again. 😊

Waiting for my another 64GB RAM to arrive tomorrow. I will try it.



发送自 Windows 10 版邮件应用

发件人: Cminer3207
发送时间: 2021年5月14日 19:21
收件人: swar/Swar-Chia-Plot-Manager
抄送: Minions; Author
主题: Re: [swar/Swar-Chia-Plot-Manager] Start error (#142)

Stagger depends on your CPU... but probably 60.
stagger_minutes: 60
max_concurrency_with_start_early: 10
concurrency_start_early_phase: 4
concurrency_start_early_phase_delay_: 0

**Comment by cocokekb** [comment]
> 

Hello!
Have you figured out the problem?
I have the same problem.
How did you decide?
