### ISSUE TITLE
Temp2 directory list of values

### ISSUE THREAD

**Issue by rlallen** [swar/Swar-Chia-Plot-Manager#151]
How can I build the list of multiple drives for the temp2 directory?

"[OPTIONAL]temporary2_directory - Can be a single value or a list of values." 

I tried comma separating, bracketing with comma separating, and quotes around two different drives and couldn't get it to work. Do you have a recommendation?

**Comment by Amneamnius** [comment]
Same as the example for destination_directory:
      - E:\Plots
      - G:\Plots
      - H:\Plots

FYI if the temp2 will be destination_directory you can just set temporary2_destination_sync to true
