### ISSUE TITLE
Need exclude final directory option

### ISSUE THREAD

**Issue by akkhara** [swar/Swar-Chia-Plot-Manager#183]
After plot is complete, it will be added final directory to chia application automatically. Which I don't want like that.

**Comment by swar** [comment]
You can always hardcode it into your downloaded copy. Otherwise, it will be out when I am done with the development branch.

**Comment by mintjustin** [comment]
> You can always hardcode it into your downloaded copy. Otherwise, it will be out when I am done with the development branch.

Can you please guide me how to do this?
Is it under plotmanager/library/commands and append "-x" to "create" in data?
