### ISSUE TITLE
Preserve job destiantion drive order through restarts

### ISSUE THREAD

**Issue by pmadison** [swar/Swar-Chia-Plot-Manager#192]
When restarting the manager, the order of destination drives is reset. 

For example:
- You have have a job named 1 whose first destination drive order is A, B, C
- You have an instance of job 1 currently running with destination A
- You restart the manager
- The next instance of job 1 will be set to destination A, but should be set to destination B

**Comment by swar** [comment]
This is great in theory, but there will be no easy way to preserve the order. A better method is instead changing destination directory to choose a destination with the least active plots.

I have already added destination filter when a drive gets too full, so this will be next on the list.

**Comment by Zoremine** [comment]
If I list my 5 drives under; destination_directory: A, B, C, D, E; Will the Manager fill the first drive and after that one gets filled move to another one?

**Comment by swar** [comment]
> If I list my 5 drives under; destination_directory: A, B, C, D, E; Will the Manager fill the first drive and after that one gets filled move to another one?

Cycles through one by one. Not when it fills up.
