### ISSUE TITLE
 raise ManagerError

### ISSUE THREAD

**Issue by ramin40686** [swar/Swar-Chia-Plot-Manager#225]
when i run the start cammand. I see this error
python manager.py start
Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "D:\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.
please help

**Comment by ramin40686** [comment]
I had the same problem and fixed by adding "chia.exe " to end of chia_location address. make sure Chia_Location in your config.yaml file to be in this format:
C:\Users\<USERNAME>\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia.exe

**Comment by swar** [comment]
It says in the error where to find the full error.

Please use GitHub Discussions for questions as this is not an Issue.
