### ISSUE TITLE
All destination plots are ?

### ISSUE THREAD

**Issue by Xefier** [swar/Swar-Chia-Plot-Manager#226]
I initially started plotting with Chia GUI then switched to Swar but even after various jobs completed from Swar all the dest drives still say plots = ?
The 4 plots is what's currently on the SSD temp directory.

![image](https://user-images.githubusercontent.com/6353352/117753976-0a167780-b1df-11eb-86e2-203b8fbea8e4.png)

**Comment by swar** [comment]
People need more information than this to help you.

Please use GitHub Discussions for questions as this is not an Issue.

**Comment by Xefier** [comment]
Seems like the most common use case is the folder will contain nothing but plot files so it should be as simple as getting number of files in directory. Or at least check the file extension of those files. Though maybe this issue has been fixed already.
