### ISSUE TITLE
not showing phase_times?

### ISSUE THREAD

**Issue by herotm** [swar/Swar-Chia-Plot-Manager#227]
===========================================================================================================
num   job    k    pid           start          elapsed_time   phase   phase_times   progress   temp_size
===========================================================================================================
1     ssd1   32   7847   2021-05-11 07:03:28   01:11:39       1                     12.63%     142 GiB
2     ssd2   32   7848   2021-05-11 07:03:28   01:11:39       1                     11.30%     136 GiB
3     ssd3   32   7849   2021-05-11 07:03:28   01:11:39       1                     10.30%     126 GiB
4     ssd1   32   8231   2021-05-11 08:15:01   00:00:06       1                     0.58%      0 GiB
5     ssd2   32   8232   2021-05-11 08:15:01   00:00:06       1                     0.58%      1 GiB
6     ssd3   32   8233   2021-05-11 08:15:01   00:00:06       1                     0.58%      1 GiB

does anybody know why

**Comment by swar** [comment]
People need more information than this to help you.

Please use GitHub Discussions for questions as this is not an Issue.
