### ISSUE TITLE
view freezing

### ISSUE THREAD

**Issue by MellianStudios** [swar/Swar-Chia-Plot-Manager#229]
hello. im on windows 10 and manager view is freezing multiple times per hour. I tried to set debug to info but there is nothing suspicious last message is 2021-05-11 18:11:33 [INFO]: Sleeping for 60 seconds. and then nothing it just freezes

**Comment by swar** [comment]
Please use GitHub Discussions for questions as this is not an Issue. 

People need way more information than this to help you.
