### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Cole\\Documents\\Swar-Chia-Plot-Manager-main\\config.yaml'

### ISSUE THREAD

**Issue by Skeezikz** [swar/Swar-Chia-Plot-Manager#233]
I have followed the steps 3 times, twice on my own, once with a video and I always get this error trying to do >python manager.py start

No one on Reddit was able to help, any one have any ideas?

**Comment by nort774** [comment]
check your file config.yaml http://www.yamllint.com/
check the path, the executable file is specified chia.exe
C:\Users\Swar\AppData\Local\chia-blockchain\app-1.1.2\resources\app.asar.unpacked\daemon\chia.exe

**Comment by swar** [comment]
Closing this ticket out because we need more information than just this.
