### ISSUE TITLE
mapping values are not allowed here

### ISSUE THREAD

**Issue by PinballPat** [swar/Swar-Chia-Plot-Manager#250]
yaml.scanner.ScannerError: mapping values are not allowed here
  in "C:\Users\Pat\Desktop\Swar-Chia-Plot-Manager-main\config.yaml", line 9, column 8

This line was not modified so I am unsure why there is an error with it?

![Capture](https://user-images.githubusercontent.com/84082752/117982515-ec363900-b2ea-11eb-9ea4-6c7c465448de.PNG)

**Comment by Cminer3207** [comment]
you have a space somewhere in your YAML file. 
After Chia Location Example:
Correct   chia_location: C;\Users\...
Incorrect chia_location:C:\Users

There must be ONE space, and one space ONLY, for all inputs.

**Comment by PinballPat** [comment]
> you have a space somewhere in your YAML file.
> After Chia Location Example:
> Correct chia_location: C;\Users...
> Incorrect chia_location:C:\Users
> 
> There must be ONE space, and one space ONLY, for all inputs.

Thanks for the help! Exactly the issue. I missed that one.
