### ISSUE TITLE
Multiple Destination Drives In Queue

### ISSUE THREAD

**Issue by Cminer3207** [swar/Swar-Chia-Plot-Manager#256]
How do you set up multiple destination drives for the plotter to sequence through?

Its easy to do multiple jobs, but this makes staggering worthless since you have to split your system up.

**Comment by swar** [comment]
There is an example with this information in the default file. This is also not an issue please use GitHub Discussions.

**Comment by Cminer3207** [comment]
Here is the answer:

In config.YAML File...

At bottom under job...

Single Drive format:
———————————
destination_directory: J:\Plots

Multiple Drive Format:
——————————
destination_directory: 
- J:\Plots
- K:\Plots
- L:\ Plots

**Comment by swar** [comment]
Hyphen separated but @Cminer3207  has the right idea

**Comment by Cminer3207** [comment]
It fills all the drives concurrently, instead of filling one and then moving on to the next.
 
D:\ 2 plot
E:\ 1 plot 
F:\ 1 plot 

etc...
