### ISSUE TITLE
The defaults feel a bit high for threads and ram

### ISSUE THREAD

**Issue by salamanders** [swar/Swar-Chia-Plot-Manager#27]
I was under the impression in the latest version that memory/threads was less.
https://chiadecentral.com/chia-plotting-improvements-in-version-1-04/ says `3389` for K32.  

I'm not sure if 8 threads is overkill, I haven't gotten a straight answer on keybase for the optimal number of threads.  I *think* 2 is a better default.

**Comment by swar** [comment]
From my experience on my SSD, 2 was a lot slower than 4 threads. But what I have in the default is just an example and should be edited to your own personal configuration. I could list a better default, but that better default would be useful for some people and not others which would put us in the same situation where we are in right now.

So I'm not sure of the correct answer on this one

**Comment by spacewaffles309** [comment]
Poking around in a few sites and videos make it look like the benefit of 2 -> 4 is much greater than 4 -> 6 or 8.  Since I've started using this, I'm going to tinker a bit and see if I reach the same conclusions.
