### ISSUE TITLE
ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by KmBooy** [swar/Swar-Chia-Plot-Manager#270]
![image](https://user-images.githubusercontent.com/35790216/118027625-b64d8f00-b394-11eb-929c-51470f0e061b.png)
![image](https://user-images.githubusercontent.com/35790216/118027239-49d29000-b394-11eb-9331-df7bfc0ebeff.png)
![image](https://user-images.githubusercontent.com/35790216/118029050-56f07e80-b396-11eb-87e0-8d732e21e22d.png)
![image](https://user-images.githubusercontent.com/35790216/118029307-9dde7400-b396-11eb-932b-d23011bbc89f.png)

An error occurs when I run  **python manager.py start** ,I don't know what the problem is and I hope to get help.

**Comment by swar** [comment]
You need a space after chia_location: and before the drive.
