### ISSUE TITLE
 Failed to start Manager.

### ISSUE THREAD

**Issue by bibiboui** [swar/Swar-Chia-Plot-Manager#271]
(venv) C:\Users\NB\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\manager.py", line 29, in <module>
    start_manager()
  File "C:\Users\NB\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at manager.log for more details on the error. It is in the same folder as manager.py.

can someone help me please thankx :)

**Comment by ddferrer** [comment]
Am getting the same error. When I look at the manager.log file it is empty (no errors). Thanks!
