### ISSUE TITLE
Plot suddenly restarted?

### ISSUE THREAD

**Issue by zpinto123** [swar/Swar-Chia-Plot-Manager#273]
Hi, I'm currently plotting 16 parallel plots with a stagger of 15 minutes between them.
For whatever reason, the plot number 16 suddenly restarted 30 minutes ago. Time elapsed was around 7h, and now it's 30 minutes ago. What might've caused this? Can I see the reason somewhere in the logs?

**Comment by zpinto123** [comment]
Also, isn't phase 1 until 31/32%? One plot is already at 34%, and it's still in phase 1. Is that normal?

**Comment by swar** [comment]
The numbers are not unique. It's just to give you a quick count
