### ISSUE TITLE
Error please help

### ISSUE THREAD

**Issue by bashar1988** [swar/Swar-Chia-Plot-Manager#280]
iam trying to do plots with SWAR since 2 days but the new plots are alyways invalid, can any one help me please and tell me where is the problem 
![image](https://user-images.githubusercontent.com/83901628/118062519-60c6b180-b397-11eb-81e0-6c8668f3878d.png)

**Comment by swar** [comment]
Please use Github Discussions but this doesn't tell us anything to be able to help you with. This is not an issue with the library.

**Comment by bashar1988** [comment]
thanks for the replay if you want some info i will provid you with it but iam not sure why it happened thats why i asking you
