### ISSUE TITLE
Running manager.py view doesn't find any active plots

### ISSUE THREAD

**Issue by paspaldzhiev** [swar/Swar-Chia-Plot-Manager#29]
Running manager.py view returns the following error:

![image](https://user-images.githubusercontent.com/8458680/116617716-d87fef80-a946-11eb-8a35-f9c8c827f5de.png)

By the looks of it, this leads me to believe that the manager is not detecting any active plots? I have a Chia GUI active and plotting +more plotting processes running via the CLI.

As far as I understand, the plot manager should automatically detect these even if they're started beforehand? Or am I wrong?

**Comment by tibble** [comment]
I have the same issue.  Plots shows ? and there aren't any listed at the top.  This is on macOS 11, using python 3.9 with venv

**Comment by tibble** [comment]
> I have the same issue. Plots shows ? and there aren't any listed at the top. This is on macOS 11, using python 3.9 with venv

==========================================================================================
num   job   k   pid   start   elapsed_time   phase   phase_times   progress   temp_size
==========================================================================================
==========================================================================================
Manager Status: Running

========================================================================
 type            drive              used     total    percent   plots
========================================================================
temp    /Volumes/chiassd1/Plot4   0.34TiB   0.91TiB   36.9%     ?    
temp2   /Volumes/chiassd1/Farm    0.34TiB   0.91TiB   36.9%     ?    
dest    /Volumes/chiassd1/Farm    0.34TiB   0.91TiB   36.9%     ?    
========================================================================
CPU Usage: 65.2%
RAM Usage: 7.10/16.00GiB(50.2%)

Plots Completed Yesterday: 0
Plots Completed Today: 0

Next log check at 2021-04-29 17:51:21

**Comment by swar** [comment]
@paspaldzhiev  can you pull the latest changes and see if that works for you? 

Also does it create any log files in the log directory you specified? If so is there any error in there? I will be working with someone having this similar issue later tonight to see if I can get to the bottom of it.

**Comment by swar** [comment]
@tibble same as what I said above if you could try the changes.

**Comment by tibble** [comment]
@swar no change.  I think this is due to the m1 native chia showing up in processes as python, not Chia.
partial example of ps output: /opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python /Users/username/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /Volumes/chiassd1/Plot4 -d /Volumes/chia

**Comment by swar** [comment]
@tibble I saw your reply on Reddit and I have to say that this was very vital information for me to debug what was going on. Thank you!

I just pushed out a commit that I think will work for you. Can you pull the latest changes and let me know if this fixed your issue?

**Comment by tibble** [comment]
It seems to have not changed, but I'm not sure I'm fully updating correct.  I cd'd to the folder, did git pull, then did 
/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python -m venv venv
. ./venv/bin/activate
then started the manager again

**Comment by swar** [comment]
@tibble are you on KeyBase by any chance? I think it might be helpful to see if I can instant message you because this seems solvable, I just don't have a means of testing solutions

**Comment by swar** [comment]
@paspaldzhiev this issue should be fixed for you. Let me know!

**Comment by paspaldzhiev** [comment]
> 
> 
> @paspaldzhiev this issue should be fixed for you. Let me know!

Yes, this works now, thank you so much!
