### ISSUE TITLE
Differente of max concurrent and concurrency

### ISSUE THREAD

**Issue by bibiboui** [swar/Swar-Chia-Plot-Manager#292]
hello every body !i have two questions
what is the different between  "max_concurrent"  and "max_concurrent_with_start_early"

and the different of "concurrency_start_early_phase" and "concurrency_start_early_phase_delay"

thanks a lot my friends

**Comment by swar** [comment]
There is documentation on the README about this. This is also not an Issue so please use discussions next time.
