### ISSUE TITLE
Notification for when manager stops

### ISSUE THREAD

**Issue by swar** [swar/Swar-Chia-Plot-Manager#30]

**Comment by Toasterme** [comment]
You can't, you have to do it yourself, on linux, every 30min i check a process, if the process is not thereit will send me an email with this simple one liner : 

`*/30 * * * * pgrep -x name_manager_process_here || echo "" | mail -s "manager is DOWN" Your_email_here`

**Comment by swar** [comment]
Agreed, closing this ticket.
