### ISSUE TITLE
[BUG] Access denied in 12hours to local drive? what is it ?

### ISSUE THREAD

**Issue by aresstokrat** [swar/Swar-Chia-Plot-Manager#319]
Traceback (most recent call last):
  File "c:\plotmanager\manager.py", line 36, in <module>
    view()
  File "c:\plotmanager\plotmanager\library\utilities\commands.py", line 106, in view
    jobs, running_work = get_running_plots(jobs=jobs, running_work=running_work)
  File "c:\plotmanager\plotmanager\library\utilities\processes.py", line 239, in get_running_plots
    temp_file_size = get_temp_size(plot_id=plot_id, temporary_directory=temporary_directory,
  File "c:\plotmanager\plotmanager\library\utilities\processes.py", line 166, in get_temp_size
    temp_size += os.path.getsize(file_path)
  File "C:\Program Files\Python39\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
PermissionError: [WinError 5] Access denied: 'e:\\plot-k32-2021-05-13-15-21-049261098c455b053f62dbf18f5647da57f196cef8e60a125e2c7930ba8525f6.plot.p2.t3.sort_bucket_121.tmp'
--------------
and then i just restart

**Comment by aresstokrat** [comment]
restarting "manager.py view"

shows everything zero, but CPU still under load, so i think its plotting... still i don't know what to do next to revive.
screen:  http://prntscr.com/12wybgh

**Comment by swar** [comment]
Windows permission issue typically. I have no idea what causes it but high CPU usage has a tendency to do that.

**Comment by aresstokrat** [comment]
I don't this its permissions. Since its working 12hours, made plots, and than this error. Today again:

http://prntscr.com/12yl9xn

"Отказано в доступе" = Access Denied
at screenshot

**Comment by swar** [comment]
High CPU is also known to deny access

**Comment by aresstokrat** [comment]
> High CPU is also known to deny access

I dont think so Swar.
I were working in PS with 12parallels 24x7, and suddenly it turnes out that it is overcloading to access denied with 6-8x parallels? Seem unlogical.
