### ISSUE TITLE
max_concurrent

### ISSUE THREAD

**Issue by Nebemires** [swar/Swar-Chia-Plot-Manager#321]
Hello!
Problem is that i cant get working max_concurrent: 12.
So i changed  from threads: 2 to  threads: 1 and  from max_concurrent: 10 to   max_concurrent: 12, max_for_phase_1:7, stagger_minutes: 30 and settings does no changed. Restarting manager does not helped. Any ideas what else i can try ?
Windows 10 Pro

**Comment by swar** [comment]
Please use Github Discussions next time. This is not an Issue with the software.
