### ISSUE TITLE
Setting max_plots to 0 or not setting at all will prevent manager to start

### ISSUE THREAD

**Issue by MaciejGorczyca** [swar/Swar-Chia-Plot-Manager#322]
Hey, changing max_plots to 0 or not setting that value (to make it go forever until disks fill) will cause error in commands.py at line 53. The error says to look for manager.log but that one is empty. Changing max_plots to anything higher than 0 will make the manager work fine. Using dev version.

**Comment by swar** [comment]
I mean you set max_plots to 0. That means you don't want any plots...

Please use Github Discussions next time. This is not an Issue with the software.
