### ISSUE TITLE
Swar view fails periodically with "OSError: [Errno 12] Not enough space"

### ISSUE THREAD

**Issue by Scorillo47** [swar/Swar-Chia-Plot-Manager#323]
I have this issue reproducing consistently on all my Windows machines. I am using Windows 10,  and Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

> Restarting view due to psutil going stale...
> Traceback (most recent call last):
>   File "manager.py", line 36, in <module>
>     view()
>   File "D:\_chia\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 123, in view
>     os.execv(sys.executable, system_args)
> OSError: [Errno 12] Not enough space
> 

Maybe the view process has perhaps a memory leak of some sort? The view gets blocked when this message appears and I have to manually restart it, after which it again works fine for a while.

**Comment by swar** [comment]
This comes down to Windows not allowing more memory to be assigned. No idea how to fix this issue, but I am moving this to Discussions
