### ISSUE TITLE
there is no way to kill a exsiting plot job @-@

### ISSUE THREAD

**Issue by KGEGE** [swar/Swar-Chia-Plot-Manager#334]
anyone konw how? my plotting disk is getting full TOT

**Comment by intdsgn** [comment]
I haven't done this yet, but according to the FAQ on the main page you should be able to view the PID number on the Plot Manager and end the corresponding task.

I assume that's (Win10) Task Manager -> Details -> sort by PID -> End Task 

Hope that helps!

**Comment by KGEGE** [comment]
yeah mam you save my ass

**Comment by KGEGE** [comment]
> I haven't done this yet, but according to the FAQ on the main page you should be able to view the PID number on the Plot Manager and end the corresponding task.
> 
> I assume that's (Win10) Task Manager -> Details -> sort by PID -> End Task
> 
> Hope that helps!

YEAH MAN YOU SAVE MY ASS

**Comment by swar** [comment]
Please use Github Discussions next time.
