### ISSUE TITLE
Question Mark Displayed for Number Of Plots on Drive

### ISSUE THREAD

**Issue by corner22** [swar/Swar-Chia-Plot-Manager#335]
I've downloaded and installed plot manager today on Windows 10. Running with chia 1.1.5.  I started the plot manager a few minutes ago and everything seems to be working OK except that when viewing my drive status it shows one of my destination drives as having 4 plots when it should display 11 and the other displays '?' plots when it should display 5.  All the pre-existing plots were generated with chia cli.  The H: drive has 11 plots in H:\ChiaPlots and the I: drive has 5 plots in folder I:\ChiaPlots. I have checked my config.yaml and it is definitely configured for these folder paths.  I have checked permissions of the folders and 'Everyone' has full access.

Is this a bug with plot manager or have I configured something wrong?

```
Manager Status: Running

=====================================================
type   drive     used     total    percent   plots
=====================================================
temp   C:      1.29TiB   1.86TiB   69.5%     1
temp   G:      0.05TiB   0.93TiB   5.6%      1
temp   D:      0.89TiB   1.82TiB   49.2%     1
temp   F:      1.90TiB   3.64TiB   52.2%     1
dest   H:      1.09TiB   7.28TiB   15.0%     4
dest   I:      0.50TiB   7.28TiB   6.8%      ?
=====================================================
```

**Comment by Kali123411** [comment]
I am also showing the same for one of my drives that already has previous plots on it.

**Comment by swar** [comment]
This is active plots, not actual plots on the drive. I don't do any scanning of your actual plots since the plot manager doesn't care about anything that exists.

Please use Github Discussions next time.
