### ISSUE TITLE
manager view no active jobs

### ISSUE THREAD

**Issue by Flekay** [swar/Swar-Chia-Plot-Manager#362]
if your not using the default filename "chia.exe" in the config.yaml no active job will be displayed

config.yaml
chia_location: C:\Users\Fleka\AppData\Local\chia-blockchain\app-1.1.5\resources\app.asar.unpacked\daemon\**chia2**.exe

you have to manualy change it in the utilities\processes.py
def get_chia_executable_name():
    return f'**chia2**{".exe" if is_windows() else ""}'

**Comment by spacewaffles309** [comment]
This seems like a highly unique situation.

**Comment by swar** [comment]
> This seems like a highly unique situation.

This is exactly my thoughts. Your best bet is to just edit the script for your use-case. This is not something I plan on prioritizing in a release.
