### ISSUE TITLE
Global max_for_phase_1?

### ISSUE THREAD

**Issue by benkywong** [swar/Swar-Chia-Plot-Manager#363]
Is it possible to add a global limit for max_for_phase_1?
I don't want to start 6 phase1 at the same time if I added 6 SSD to the PC, thanks

**Comment by benkywong** [comment]
also global stagger, it is no good that 3 plots finish time within 10min, it takes time to copy to NAS or other HDD

**Comment by swar** [comment]
If you would like to go ahead and make a pull request with these features, I will gladly review.
