### ISSUE TITLE
How to remove missing plots from history

### ISSUE THREAD

**Issue by delucca** [swar/Swar-Chia-Plot-Manager#385]
Hi everyone

Amazing job! Also, impressive speed :) Thanks for this great tool!

I've started using it in my Linux server today. I accidentally launched the manager before updating the config, and that kicked off the default plots.

After a few minutes I saw what I did wrong and updated the config.yaml file, but now my `manager view` is like the following:
```
========================================================================================================================
num          job          k    pid           start          elapsed_time   phase   phase_times   progress   temp_size
========================================================================================================================
1     ?                   32   5067   2021-05-15 13:52:58   00:10:52       1                     0          0 GiB
2     ?                   32   5068   2021-05-15 13:52:58   00:10:52       1                     0          0 GiB
3     xch-001-d41f-de9d   32   6331   2021-05-15 14:03:41   00:00:10       1                     0.58%      1 GiB
========================================================================================================================
```

Probably this happened because I removed the files that the default jobs generated manually.

How can I clear my view (without affecting already running jobs)?

By clear, I mean, remove the line 1 and 2 that are pointing to missing jobs.

**Comment by DM4DS** [comment]
@delucca : If you stopped the plot processes and the manager. Delete the LOG Files from that jobs and then start your manager
                  again, also the view.

Don´t forget to delete the TEMP files generated by the jobs.

**Comment by delucca** [comment]
> @delucca : If you stopped the plot processes and the manager. Delete the LOG Files from that jobs and then start your manager
> again, also the view.
> 
> Don´t forget to delete the TEMP files generated by the jobs.

Thanks! It worked :)
