### ISSUE TITLE
[FR] Add ability to plot+delete (replace plots function)

### ISSUE THREAD

**Issue by Hukuma1** [swar/Swar-Chia-Plot-Manager#394]
Awesome job with Swar! Thanks for this tool.

With the upcoming re-plotting requirement for pools, the suggested path is to delete a few plots and plot new ones so you solo farm + pool farm at the same time (that is, instead of simply deleting all plots at the same time and starting from scratch).

To make this even more efficient, could it be possible to add a function to Swar to make plots, and once it's 100% ready to copy the new plot over, have it delete 1 on the destination drive? This way you get to farm on a full HDD more effectively than deleting 4-5 plots and waiting for new plots to be generated. Not to mention this would be automated and you wouldn't have to babysit the deletion process in fear of running out of space upon copy.

**Comment by Mar-85** [comment]
Wow I love this idea, i've been wondering how im going to manage this. This makes it perfect.
Also to add to this, I think it would be a great idea to have it plot the new pool plots to the remaining free space available...when it runs out of free space then start plotting and deleting the old plots.

**Comment by swar** [comment]
This is a planned feature already later down the road. As pooling plots got delayed, it will still be on the back burner.

**Comment by Mar-85** [comment]
> This is a planned feature already later down the road. As pooling plots got delayed, it will still be on the back burner.

Thats fair enough. Hopefully they make it easy to distinguish new from old plots types so the plot manager can automate after all the drives are full and circle back without having any intervention.

**Comment by Hukuma1** [comment]
Darn, was hoping it would be implemented a bit sooner. This feature would also help anyone trying to pool to a different private key/wallet for example.

Pooling support is supposedly coming by the end of the month from Chia.

Either way, closing this out for now. Thanks and keep up the great work!
