### ISSUE TITLE
Add the capability to suspend plotting

### ISSUE THREAD

**Issue by RealAwesomeness** [swar/Swar-Chia-Plot-Manager#397]
Add capability to suspend plots that are in stages 1 and 2 if the total drive space is less than some percentage(5%?) in windows.
Shouldn't be that hard if we just use [this](https://stackoverflow.com/questions/18984666/how-do-i-get-a-subprocess-to-suspend-execution-of-an-external-program-every-5-se#27007047) to suspend processes. Just need to read the amount of remaining space on the temp drive every interval and suspend/resume processes as needed based on their stage.

**Comment by swar** [comment]
There's way too much that needs to be written to get something like this working. Sure suspending a plot is easy, but the logic of when to do it based on the size / resource usage / etc is just not something I think I want to tackle.

**Comment by RealAwesomeness** [comment]
Can't you just loop through jobs and check if the temp drive is almost full and that the job is in phases 1 or 2? I would do it but I don't really understand your code because you don't use classes for the jobs.
________________________________

**Comment by swar** [comment]
In that case, I think you should use parts of my code and adhere it to what you want to do.
