### ISSUE TITLE
viewer crashing

### ISSUE THREAD

**Issue by cryptors** [swar/Swar-Chia-Plot-Manager#42]
I installed everything on an ubuntu server 20.04,
but when I start the manager viewer (python manager.py view) after 2 refreshes it crashes with this error.
If I put the refresh time for 60sec, i will refresh once, but the second time it stops. Same for any refresh value.

Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "/chia/chia-manager/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 123, in view
    os.execv(sys.executable, system_args)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by swar** [comment]
What OS is this on and did you make a virtual environment for Python?

**Comment by karlshea** [comment]
Also on Ubuntu server 20.04, running in a venv. This is the error I'm getting:

```
Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 4, in <module>
    from plotmanager.library.utilities.commands import start_manager, stop_manager, view, analyze_logs
  File "/opt/chia-plot-manager/plotmanager/library/utilities/commands.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by mjsr** [comment]
After doing `python -m venv venv` and `. ./venv/bin/activate` (or equivalent for Windows), you need to run `pip install -r requirements.txt`.

The requirements file contains psutil as a dependency: https://github.com/swar/Swar-Chia-Plot-Manager/blob/main/requirements.txt

Means you didn't install these.

**Comment by karlshea** [comment]
I did, but I think something's messed up with my python install. I'm running Chia under Docker anyways, and I don't think plot manager really likes that either.

**Comment by gntz555** [comment]
I have a similar issue: https://github.com/swar/Swar-Chia-Plot-Manager/issues/65#issue-873994038

Latest python and pip is installed...

**Comment by swar** [comment]
> I did, but I think something's messed up with my python install. I'm running Chia under Docker anyways, and I don't think plot manager really likes that either.

Unfortunately I have not tried this with docker so I'm not sure what issues could pop-up in relation to that

**Comment by karlshea** [comment]
> > I did, but I think something's messed up with my python install. I'm running Chia under Docker anyways, and I don't think plot manager really likes that either.
> 
> Unfortunately I have not tried this with docker so I'm not sure what issues could pop-up in relation to that

FYI this is what was in the script I pointed `chia_location` to:

```
#!/usr/bin/env bash

docker-compose -f /srv/chia/docker-compose.yml exec chia venv/bin/chia "${@}"
```

It fired off the job okay and was showing the job in the viewer, but then seemed to lose track of what was going on. I'm guessing if you're checking pids that my psutil problem is the issue, but since I'm only plotting 2 concurrent I didn't think it was worth fixing whatever was going on with python. Just wanted to post the script in case it helps someone else!

**Comment by mahonni** [comment]
Same here, in my case, I'm not using docker, just plain Ubuntu 20.04LTS.

```
Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 4, in <module>
    from plotmanager.library.utilities.commands import start_manager, stop_manager, view, analyze_logs
  File "/home/mboher/chi/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

Any idea or workaround?

I created another issue, but it's the same as @karlshea, so I closed it (https://github.com/swar/Swar-Chia-Plot-Manager/issues/76)

**Comment by lastb0isct** [comment]
I'm getting the same error - the viewer runs for a few minutes and then crashes saying:
```
Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 4, in <module>
    from plotmanager.library.utilities.commands import start_manager, stop_manager, view, analyze_logs
  File "/root/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

It seems that it might be because the processes I started were outside of this utility though...not entirely sure.  I didn't start those with proper log locations.  I will wait for these to finish and then do more testing with the utility.

**Comment by karlshea** [comment]
venv seems to be a way for python to install dependencies in a "container" but at least on Linux it doesn't seem to work... I finally installed the python3-psutil package and the error went away. Now the new error is `No module named 'dateparser'`.

This just reminds me of the hell that was developing in Ruby.

**Comment by lastb0isct** [comment]
> venv seems to be a way for python to install dependencies in a "container" but at least on Linux it doesn't seem to work... I finally installed the python3-psutil package globally and the error went away. Now the new error is `No module named 'dateparser'`.
> 
> This just reminds me of the hell that was developing in Ruby.

Didn't make a difference for me on RHEL7...mighht be an issue because I have multiple different versions of python installed though.

**Comment by elforesto** [comment]
I went one step further and installed inside of the Docker container, same issue comes up.

**Comment by elforesto** [comment]
> venv seems to be a way for python to install dependencies in a "container" but at least on Linux it doesn't seem to work... I finally installed the python3-psutil package globally and the error went away. Now the new error is `No module named 'dateparser'`.
> 
> This just reminds me of the hell that was developing in Ruby.

I went down this rabbit hole installing dependencies container-wide in Docker, then ran into the wall that discord_notify lacks a package in apt.

**Comment by karlshea** [comment]
I gave up on the docker image—since I already needed python installed on the host, and chia uses a venv itself, I just installed chia normally. Along with my fix in #197 the plot manager now works well.

**Comment by Feromrk** [comment]
I get this error too:
```
Restarting view due to psutil going stale...
Traceback (most recent call last):
  File "manager.py", line 36, in <module>
    view()
  File "/home/johannes/repos/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 123, in view
    os.execv(sys.executable, system_args)
FileNotFoundError: [Errno 2] No such file or directory
```
Ubuntu 20.04.2 LTS, followed the install instructions (including venv).

**Comment by 8465231** [comment]
Also getting this same error as the others. Installed globally.

**Comment by Polirer** [comment]
Getting the same error in windows 10. Any guidance on how to get the "view" working again? I did install the requirements.txt . View was working fine all day until now. Thanks for the help.

**Comment by Tchlix** [comment]
Hardcoding path to python interpreter in commands.py view() fixed the problem for me.

system_args = ["/usr/bin/python3"] + sys.argv
os.execv("/usr/bin/python3", system_args)

**Comment by 8465231** [comment]
is that a fix for windows or ubuntu?
