### ISSUE TITLE
Feature Request - Remaining plots to go

### ISSUE THREAD

**Issue by Gregwolf3030** [swar/Swar-Chia-Plot-Manager#456]
It would be nice to be able to see in the viewer how many plots have been completed out of the assigned "Max Plots". This would give the user an insight of how far into the current task it is. Maybe if they assigned 100 max plots, it could show "15/100" (meaning it has completed 15 out of the 100).

Thank you. This tool has been great to use. Looking forward to future releases.

**Comment by swar** [comment]
Unfortunately the way that this works, it will not be entirely possible to get this added. Manager and view run separately and are not aware of the others doings. Because of this, view cannot keep an accurate count because manager may or may not have been restarted during the process.
