### ISSUE TITLE
View not matching paths, displaying ? in drives table (Ubuntu)

### ISSUE THREAD

**Issue by thatramenpanda** [swar/Swar-Chia-Plot-Manager#46]
manager view not matching paths with CLI, displaying ? in drives table instead

Ubuntu 20.04

![image](https://user-images.githubusercontent.com/12022115/116751024-50a7ed00-a9fb-11eb-9df8-4ad44943df8d.png)

Processes:
5287 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-1TB/ChiaPlotting -d /drives/hddbay01/ChiaPlots -r 6 -u 128 -2 /drives/hddbay01/ChiaPlots -f XXX -p YYY
5288  /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-2TB/ChiaPlotting -d /drives/hddbay04/ChiaPlots -r 6 -u 128 -2 /drives/hddbay04/ChiaPlots -f XXX -p YYY
5589  /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-1TB/ChiaPlotting -d /drives/hddbay02/ChiaPlots -r 6 -u 128 -2 /drives/hddbay02/ChiaPlots -f XXX -p YYY
5590 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-2TB/ChiaPlotting -d /drives/hddbay03/ChiaPlots -r 6 -u 128 -2 /drives/hddbay03/ChiaPlots -f XXX -p YYY
63472 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-2TB/ChiaPlotting -d /drives/hddbay05/ChiaPlots -r 5 -u 128 -2 /drives/hddbay05/ChiaPlots -f XXX -p YYY
64000 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-2TB/ChiaPlotting -d /drives/hddbay04/ChiaPlots -r 5 -u 128 -2 /drives/hddbay04/ChiaPlots -f XXX -p YYY
65561 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-1TB/ChiaPlotting -d /drives/hddbay03/ChiaPlots -r 5 -u 128 -2 /drives/hddbay03/ChiaPlots -f XXX -p YYY
67436 /home/chiaharvester/chia-blockchain/venv/bin/python3.8 /home/chiaharvester/chia-blockchain/venv/bin/chia plots create -k 32 -b 4000 -t /drives/rocket-1TB/ChiaPlotting -d /drives/hddbay04/ChiaPlots -r 5 -u 128 -2 /drives/hddbay04/ChiaPlots -f XXX -p YYY

**Comment by swar** [comment]
I am in talks with @thatramenpanda  in trying to get this one solved!
