### ISSUE TITLE
[low prio view bug] elapsed_time wrong for plots longer than 24h

### ISSUE THREAD

**Issue by TomTom0815** [swar/Swar-Chia-Plot-Manager#470]
I'm running some high speed plots on NVME and a low speed on SSDs. Yes, I know, I overdid it on SSDs jobs in parallel ;) - but the plot finished after 26 hours ...

I realized that the 'elapsed_time' is jumping back to 00:00:00 instead of keep counting upwards after 24:00:00. 

It's only a minor bug which probably doesn't effect a lot of users. (I'm fine when you close the bug again - I just wanted to make you aware) - Great job on the tool. Thanks.

**Comment by swar** [comment]
Fixed in development branch
