### ISSUE TITLE
Not seeing plot complete notifications  [notify_discord]  

### ISSUE THREAD

**Issue by modsoft** [swar/Swar-Chia-Plot-Manager#48]
notify_discord will successfully send an initial 'Plot Manager has started on....' message when the plot manager is started.
However, no further notifications will occur. 
Plots are completing but I'm not getting any further subsequent messages for plot completion.

**Comment by swar** [comment]
@wolfrage76 Do you know if this worked for you recently?

Wolf is the person behind the discord notifications so he may be able to provide some insight on it.

**Comment by wolfrage76** [comment]
@modsoft It is working for me currently, I have been getting notices all day on plot completion.   Are you on windows or linux or OSX?

**Comment by modsoft** [comment]
Hey ! thanks for your reply, and for this awesome tool.
I am on Linux, Ubuntu 21.04
I tried re-starting the manager with Push notifications as well.
I received a push and a discord notification for 'manager start...'
12 plots completed in the last 24 hours, and I only receive done 'plot complete' notification in that time, both push and discord.

happy to post my config. I have manager: check_interval 30 and  view: check_interval 30.

**Comment by wolfrage76** [comment]
Hmm, I had it off recently on my Linux machine so I turned it on to test.  I will check it once I have a plot complete on it to see if I'm getting notices in Linux -- it's been working in Windows.  

Also, what python version are you using, jic?

**Comment by wolfrage76** [comment]
Looks like it worked for me:
![image](https://user-images.githubusercontent.com/75458290/116834234-18cfaf80-ab8b-11eb-8f76-b7501cc46c80.png)

Not sure why you'd see the first at startup but not at time of completion.  Maybe set logging to info and see if it says anything?

**Comment by gntz555** [comment]
> @modsoft It is working for me currently, I have been getting notices all day on plot completion. Are you on windows or linux or OSX?

I have the same Issue with the discord notification.

**Comment by wolfrage76** [comment]
@swar I'll do a code comparison later to see if there's anything different in the codebase vs what I'm running.

**Comment by gntz555** [comment]
[WD_Book_2021-05-03_14_12_26_272761.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414844/WD_Book_2021-05-03_14_12_26_272761.log)
[WD_Book_2021-05-03_14_13_26_293663.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414846/WD_Book_2021-05-03_14_13_26_293663.log)
[WD_Book_2021-05-03_14_14_26_305786.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414847/WD_Book_2021-05-03_14_14_26_305786.log)
[micron_2021-05-03_13_34_20_480000.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414848/micron_2021-05-03_13_34_20_480000.log)
[micron_2021-05-03_13_35_20_498366.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414849/micron_2021-05-03_13_35_20_498366.log)
[micron_2021-05-03_13_36_20_511503.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414850/micron_2021-05-03_13_36_20_511503.log)
[micron_2021-05-03_13_37_20_523808.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414851/micron_2021-05-03_13_37_20_523808.log)
[WD_Book_2021-05-03_14_11_26_159909.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414852/WD_Book_2021-05-03_14_11_26_159909.log)

**Comment by paumrch** [comment]
> Looks like it worked for me:
> ![image](https://user-images.githubusercontent.com/75458290/116834234-18cfaf80-ab8b-11eb-8f76-b7501cc46c80.png)
> 
> Not sure why you'd see the first at startup but not at time of completion. Maybe set logging to info and see if it says anything?

HI! Thanks for your work, 

I'm only receiving Plot Complete notification. 

How could I set notifications for... a XCH Block Reward, or receive plotting status every hour in Discord... 

Thanks! I think it could be very useful.

**Comment by wolfrage76** [comment]
> How could I set notifications for... a XCH Block Reward, or receive plotting status every hour in Discord...

That wouldn't be added to this as the notifications are, and will continue to be, geared towards Plotting notifications.  Here are 2 tools though (@swar delete if not allowed, not trying to hijack):
https://github.com/wolfrage76/chiaWalletMonitor (mine)
https://github.com/joaquimguimaraes/chiabot (third-party)

**Comment by wolfrage76** [comment]
> [WD_Book_2021-05-03_14_12_26_272761.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414844/WD_Book_2021-05-03_14_12_26_272761.log)
> [WD_Book_2021-05-03_14_13_26_293663.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414846/WD_Book_2021-05-03_14_13_26_293663.log)
> [WD_Book_2021-05-03_14_14_26_305786.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414847/WD_Book_2021-05-03_14_14_26_305786.log)
> [micron_2021-05-03_13_34_20_480000.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414848/micron_2021-05-03_13_34_20_480000.log)
> [micron_2021-05-03_13_35_20_498366.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414849/micron_2021-05-03_13_35_20_498366.log)
> [micron_2021-05-03_13_36_20_511503.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414850/micron_2021-05-03_13_36_20_511503.log)
> [micron_2021-05-03_13_37_20_523808.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414851/micron_2021-05-03_13_37_20_523808.log)
> [WD_Book_2021-05-03_14_11_26_159909.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6414852/WD_Book_2021-05-03_14_11_26_159909.log)
> 
> The INFO logs so far.

Sorry, i meant the manager.log file from the script root that is generated with any errors

**Comment by paumrch** [comment]
> > How could I set notifications for... a XCH Block Reward, or receive plotting status every hour in Discord...
> 
> That wouldn't be added to this as the notifications are, and will continue to be, geared towards Plotting notifications. Here are 2 tools though (@swar delete if not allowed, not trying to hijack):
> https://github.com/wolfrage76/chiaWalletMonitor (mine)
> https://github.com/joaquimguimaraes/chiabot (third-party)

That's great.

I could install both without stopping plotting and farming? 

Thank you.

**Comment by wolfrage76** [comment]
@gntz555 @modsoft What version of Python are you running?  I reset my code to current Main and I am receiving notifications of Starting the manager and plot completions on both windows and linux.

**Comment by gntz555** [comment]
> @gntz555 @modsoft What version of Python are you running? I reset my code to current Main and I am receiving notifications of Starting the manager and plot completions on both windows and linux.

The most recent one. My Windows  is a few days old. The python installation is 1 or 2 days old.

[manager.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6417529/manager.log)

**Comment by modsoft** [comment]
> @gntz555 @modsoft What version of Python are you running? I reset my code to current Main and I am receiving notifications of Starting the manager and plot completions on both windows and linux.

@wolfrage76 , 
Thank you, I am running python 3.9.4. manager.log is empty.
So, my notifications are now working fine. I am not sure what changed however. I restarted my PC, added Push notification settings. restarted the manager a few times with different settings yesterday. and for some reason I am now getting plot complete notifications on both Push and Discord. So, feel free to close this issue.
