### ISSUE TITLE
can you provide some examples

### ISSUE THREAD

**Issue by gdtiti** [swar/Swar-Chia-Plot-Manager#49]
May I ask the specific hardware configuration and program corresponding to de configuration, can you provide some examples? The overall feeling of self-configuration efficiency is not particularly high.

**Comment by raid5** [comment]
This is better situated for Discussions (https://github.com/swar/Swar-Chia-Plot-Manager/discussions) or Keybase.

**Comment by swar** [comment]
Agreed with what @raid5  said.

**Comment by swar** [comment]
Can't really provided questions on hardware specifics when I only have one hardware. But hey if you want to donate hardware, I'll take it ;)
