### ISSUE TITLE
How to gracefully stop the plot manager?

### ISSUE THREAD

**Issue by modsoft** [swar/Swar-Chia-Plot-Manager#50]
Hey!
I have plots continually kicking off and completing.
however if I want to edit config, add new destinations, etc.
Is there a way to  stop new jobs from occurring? so I can wait for remaining jobs to finish before stopping the manager.
Thanks,

**Comment by stubmirror** [comment]
save your new config

ctrl c to get out of viewer.
python manager.py stop
python manager.py start
python manager.py view

but dont change directories of running jobs is what i was told.
stopping and starting the manager has worked fine, after changing other parameters and adding jobs. it shouldnt interupt running jobs.

**Comment by mjsr** [comment]
I think it would be a great addition of a `python manager.py reload-config` or something like this.

**Comment by swar** [comment]
> save your new config
> 
> ctrl c to get out of viewer.
> python manager.py stop
> python manager.py start
> python manager.py view
> 
> but dont change directories of running jobs is what i was told.
> stopping and starting the manager has worked fine, after changing other parameters and adding jobs. it shouldnt interupt running jobs.

This is absolutely correct.



> I think it would be a great addition of a `python manager.py reload-config` or something like this.

This can be done with `python manager.py restart`

**Comment by modsoft** [comment]
OK good to know, I can confidently close the manager with active jobs, and they will complete.
Thanks!
