### ISSUE TITLE
non-hexadecimal number found in fromhex() arg at position 0

### ISSUE THREAD

**Issue by mbatorowicz** [swar/Swar-Chia-Plot-Manager#54]
Hello, after running "python3 manager.py start" the logs show this entry:

Traceback (most recent call last):
File "chia/cmds/chia.py", line 81, in <module>
File "chia/cmds/chia.py", line 77, in main
File "click/core.py", line 829, in call
File "click/core.py", line 782, in main
File "click/core.py", line 1259, in invoke
File "click/core.py", line 1259, in invoke
File "click/core.py", line 1066, in invoke
File "click/core.py", line 610, in invoke
File "click/decorators.py", line 21, in new_func
File "chia/cmds/plots.py", line 135, in create_cmd
File "chia/plotting/create_plots.py", line 55, in create_plots
ValueError: non-hexadecimal number found in fromhex() arg at position 0
[48842] Failed to execute script chia

**Comment by mjsr** [comment]
Disclaimer: I'm a new user of this plot manager and I'm just trying to help.

The stack trace you shared looks like it is from the chia project itself. The last line in the stack trace pointing to a file: `File "chia/plotting/create_plots.py", line 55, in create_plots`, points to [this line of code](https://github.com/Chia-Network/chia-blockchain/blob/a56796c5878efdf14db7c2b426800e4a1113d741/chia/plotting/create_plots.py#L55) in the chia-blockchain repo:

```
farmer_public_key = G1Element.from_bytes(bytes.fromhex(args.farmer_public_key))
```

My guess is that you have a typo/wrong farmer public key in the plot manager's config.yaml file. Check the lines with `farmer_public_key` and `pool_public_key` and make sure they match the farmer public key and pool public key from running `chia keys show` in your Chia installation.

**Comment by mbatorowicz** [comment]
As I deleted the keys from config.yaml it worked. Will he then use my appropriate keys?

**Comment by mjsr** [comment]
If you are running a full node locally, you don't have to specify the `farmer_public_key` and `pool_public_key` (the documentation comments in the config clarify these are optional).

> Will he then use my appropriate keys?

My understanding is: yes. In my main machine which runs a full node, I didn't add the farmer or pool keys. Since you're pointing to the Chia installation, it's all good. If you have another machine plotting, that's where you want to set the farmer and pool public keys.

Happy plotting!

**Comment by birdonwheels5** [comment]
The public and farmer keys have to be in hex format. The gui wallet (at least on windows) lets you get at that if you click the eye icon to show the private keys. The public key in hex will be there. I had this same issue and I don't think it's in the documentation anywhere.
