### ISSUE TITLE
Feature: Initial Job wait time

### ISSUE THREAD

**Issue by Piet0816** [swar/Swar-Chia-Plot-Manager#549]
I am plotting with 6 different jobs on 6 ssds. It would be nice to configure an initial wait time for each job, so the first batch does not end all at the same time.

This is not a problem when running for some days straight, but always when starting new plots after a restart.

**Comment by pulseOXE** [comment]
+1 - This is the entire reason I want to use a manager to do this. I'm running 10 Jobs across 9 partitions, and I want the wait time to function exactly as you do. One job kickoff at a time every time interval (for me an hour) until all plots are running.

**Comment by Falacio** [comment]
+1 
I have same need... I'd like to kick some plots with certain delay, and after a number, launch a new job as soon as the last one finishes

**Comment by swar** [comment]
Try version 0.1.0.
https://github.com/swar/Swar-Chia-Plot-Manager/releases/tag/v.0.1.0

**Comment by Piet0816** [comment]
Exactly what i needed. Thanks.
