### ISSUE TITLE
huge problem occurred, all machines same problem

### ISSUE THREAD

**Issue by b9t2q6** [swar/Swar-Chia-Plot-Manager#559]
File "/data/Plot-Manager/plotmanager/library/utilities/log.py", line 77, in analyze_log_dates
    analysis = _get_date_summary(analysis)
  File "/data/Plot-Manager/plotmanager/library/utilities/log.py", line 36, in _get_date_summary
    end_date = analysis['files'][file_path]['data']['date'].date()
AttributeError: 'NoneType' object has no attribute 'date'

same problems  when  use pythoh manager.py view,     manager is still running,

**Comment by asukahan** [comment]
I would have a try to change date format to US.

**Comment by b9t2q6** [comment]
thanks man, solved

**Comment by VictorVolpe** [comment]
> 
> 
> I would have a try to change date format to US.

How to do on Debian 10?

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
