### ISSUE TITLE
Indicate Destination Drive in main table.

### ISSUE THREAD

**Issue by asukahan** [swar/Swar-Chia-Plot-Manager#560]
I would like a feature that could indicate destination for each job. then I could manage my goodsync or rsync to move my file without interrupting phase 5 for coming jobs.

**Comment by Lyushen** [comment]
U can do it by another way, create symbolic link, set the destination as folder, and change link (folder) to what you need. It flex enough for this porpuses.
By the way, what cloud do you use?

**Comment by swar** [comment]
Will be awaiting your pull request with the functionality. 😄

**Comment by asukahan** [comment]
> Will be awaiting your pull request with the functionality. 😄

seems it's already in 0.1.0
