### ISSUE TITLE
python manager.py start problems

### ISSUE THREAD

**Issue by LaHood0815** [swar/Swar-Chia-Plot-Manager#58]
(venv) xyz@UBUNTUCHIA:~/Swar-Chia-Plot-Manager$ python manager.py start

Traceback (most recent call last):
  File "manager.py", line 29, in <module>
    start_manager()
  File "/home/xyz/Swar-Chia-Plot-Manager/plotmanager/library/utilities/commands.py", line 32, in start_manager
    notification_settings, debug_level, view_settings = get_config_info()
  File "/home/xyz/Swar-Chia-Plot-Manager/plotmanager/library/parse/configuration.py", line 102, in get_config_info
    config = _get_config()
  File "/home/xyz/Swar-Chia-Plot-Manager/plotmanager/library/parse/configuration.py", line 16, in _get_config
    config = yaml.load(stream=f, Loader=yaml.Loader)
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/xyz/Swar-Chia-Plot-Manager/venv/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/home/xyz/Swar-Chia-Plot-Manager/config.yaml", line 6, column 1
expected <block end>, but found '<block sequence start>'
  in "/home/xyz/Swar-Chia-Plot-Manager/config.yaml", line 155, column 2

config.yaml

chia_location: /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia
  check_interval: 60
  log_level: ERROR
  folder_path: /.chia/mainnet/plotter

  check_interval: 60
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true

  notify_discord: false
  discord_webhook_url: https://discord.com/api/webhooks/0000000000000000/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

  notify_sound: false
  song: audio.mp3

  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx

  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890

  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88

  max_concurrent: 18

  - name: 2TB_001
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /dev/nvme0n1p2
    temporary2_directory:
    destination_directory: /dev/sdi2
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 7700
    max_concurrent: 5
    max_concurrent_with_start_early: 5
    stagger_minutes: 90
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

 - name: 2TB_002
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /dev/nvme1n1p2
    temporary2_directory:
    destination_directory: /dev/sdc2
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 7700
    max_concurrent: 5
    max_concurrent_with_start_early: 5
    stagger_minutes: 90
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    
  - name: 1_6TB_003
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /dev/nvme2n1
    temporary2_directory:
    destination_directory: /dev/nvme2n1
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 7700
    max_concurrent: 4
    max_concurrent_with_start_early: 4
    stagger_minutes: 90
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    
  - name: 1_6TB_004
    max_plots: 999
    farmer_public_key:
    pool_public_key:
    temporary_directory: /dev/nvme3n1
    temporary2_directory:
    destination_directory: /dev/nvme3n1
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 7700
    max_concurrent: 4
    max_concurrent_with_start_early: 4
    stagger_minutes: 90
    max_for_phase_1: 1
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

**Comment by spacewaffles309** [comment]
Are you sure that's all of the config.yaml?  The last two errors are referencing Row 6 and 155, but row 6 seems ok and there isn't a row 155 in what you've pasted there.

**Comment by LaHood0815** [comment]
i deleted that commented part of the configfile. I attach the original one here with all lines.
[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6411731/config.txt)

**Comment by spacewaffles309** [comment]
Ok, I figured it was comments but just wanted to be thorough.  Line 155, the first part " - " seems to be a little different than the other sections, so I copy/pasted from the other jobs to match the space/blank/tab/etc.  For line 6 though, not sure yet.  Everything in there looks ok.

[config2.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6411862/config2.txt)

**Comment by swar** [comment]
@LaHood0815  yes your config.yaml is not formatted properly. I think @spacewaffles309 has the correct suggestion. here.

**Comment by LaHood0815** [comment]
ok, i have no idea how the format should look like. But i found a turnaround and installed all under windows and now it works.
