### ISSUE TITLE
Failed to start Manager.

### ISSUE THREAD

**Issue by 0x13ens** [swar/Swar-Chia-Plot-Manager#60]
python manager.py start

```
c:\Users\benm7\Desktop\Swar-Chia-Plot-Manager>python manager.py start
Traceback (most recent call last):
  File "c:\Users\benm7\Desktop\Swar-Chia-Plot-Manager\manager.py", line 29, in <module>
    start_manager()
  File "c:\Users\benm7\Desktop\Swar-Chia-Plot-Manager\plotmanager\library\utilities\commands.py", line 47, in start_manager
    raise ManagerError('Failed to start Manager.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager.
```

**Comment by garthheff** [comment]
Hey mate, you just updated CHIA but forgot to update the new path in the config.yaml, as the path has the version included..

**Comment by swar** [comment]
@0x13ens what's your manager.log say? I also updated the script a bit recently so you may want to git pull.

**Comment by garthheff** [comment]
> @0x13ens what's your manager.log say? I also updated the script a bit recently so you may want to git pull.

Hey I got this error message after I upgraded chia, as the path to chia.exe in windows changes on a upgrade. Might want to add a check to make sure the file exists and if not display an error to check the chia_location path in the config.yaml

**Comment by 0x13ens** [comment]
Thanks, everyone! it was indeed the config file chia version.
