### ISSUE TITLE
I have the config file set for 6 concurrent downloads, but only getting 4

### ISSUE THREAD

**Issue by lpenrod** [swar/Swar-Chia-Plot-Manager#61]
Do I have something in there wrong?  Here is the relevant part of the config.yaml file (I've just changed the keys, have actual keys in there and they are farming nicely):

  - name: chia2_plotter
    max_plots: 999
    farmer_public_key: [key]
    pool_public_key: [key]
    temporary_directory: D:\
    temporary2_directory:
    destination_directory: Z:\
    size: 32
    bitfield: true
    threads: 2
    buckets: 128
    memory_buffer: 4000
    max_concurrent: 6
    max_concurrent_with_start_early: 7
    stagger_minutes: 60
    max_for_phase_1: 2
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

![image](https://user-images.githubusercontent.com/20890940/116813808-5268d200-ab1b-11eb-8871-b19025225ff3.png)

I just noticed in the above picture that a fifth on just kicked off.   It was 4 when I began writing this.   I have a second rig with the same configuration and it's at 4 plots running concurrently.  The CPU's not running ploys are basically idle.

BTW, I love your software!  Before I was using powershell and kicking off 6 instances with an hour sleep inbetween.  Over days, they were getting in sync with their phases.

**Comment by DaT1ck** [comment]
You have it set so that the max number of plots in phase 1 is 2.  From the screenshot it looks like there are two in that phase already, so the next one wont start until both the stagger time and max in phase conditions have been met.

**Comment by swar** [comment]
@DaT1ck  is correct!

**Comment by garthheff** [comment]
Set concurrency_start_early_phase from 4 to 6. 
 "The maximum number of plots to have for this job at any given time including phases that started early"

**Comment by lpenrod** [comment]
Thanks for the input!
