### ISSUE TITLE
viewer instability

### ISSUE THREAD

**Issue by spacewaffles309** [swar/Swar-Chia-Plot-Manager#62]
I didn't get a chance to grab this as text, but I did get a quick screenshot before the window locked up and died - please see attached.

I have this script running on a few different machines, slightly different hardware, but all still fairly new and beefy specs.  I've tailored the config.yaml for each one so that they shouldn't be getting slammed too hard with jobs, but this error has hit the majority of them at least once over the last few days.  I first really started setting up and using this on Apr 30.

I've noticed it doesn't seem to happen as often since lowering the chia.exe launched process priority from realtime to normal, but it was showing again on one machine when I woke up this morning and checked on things.

So far I greatly enjoy using this project, but I just wish I knew more about python to really help fix things.  Windows 10 20H2 Enterprise, build 19042.928, on all machines. 

![Image1](https://user-images.githubusercontent.com/83542966/116816060-6538d200-ab2e-11eb-9a57-35a32437f160.png)

**Comment by swar** [comment]
Hmmm I'll keep this ticket open so I can look into it further.

Your manager still keeps working though right?

**Comment by spacewaffles309** [comment]
Yes, but Python gets pretty wild for a while with constantly spawning more and more subprocesses that are difficult to terminate.  Eventually even those seem to close themselves out.

As today has gone on, I haven't seen it happen yet, but I've been doing a lot of tweaks, restarting the manager and machine reboots to get every plotter on the same page.

**Comment by swar** [comment]
Upgrade to the newest version and see if it helps, if it doesn't help then I'm not sure. Because it could be a whole lot of factors including Windows. I've seen someone with this issue that had it occur on 1 PC and the only difference on that PC was that they had multiple users. That could be a factor. This will need to be something you work through or ask on the Discussions board.
