### ISSUE TITLE
Manager view stuck on windows without showing anything

### ISSUE THREAD

**Issue by Toasterme** [swar/Swar-Chia-Plot-Manager#63]
So i did the cd + activate the venv per instruction, when i start the manager it is running in the background, but the view is stuck there without showing anything ?  tried with powershell, same thing.

![image](https://user-images.githubusercontent.com/732881/116817291-91a31d00-ab33-11eb-8069-e5ea842538d8.png)

The logs from the plots are there, and updating... 
But the manager.log is there too but empty.  Is there a way to force verbose logging to this particular process ?  i see the stateless-manager.py running...

In the meantime i've right click on the process and created a memory dump , then analyse it with WinDBG  : 

*** ERROR: Symbol file could not be found.  Defaulted to export symbols for python38.dll - 
*** ERROR: Module load completed but symbols could not be loaded for pythonw3.8.exe
DEFAULT_BUCKET_ID:  STATUS_BREAKPOINT
PROCESS_NAME:  pythonw3.8.exe
ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.
EXCEPTION_CODE: (HRESULT) 0x80000003 (2147483651) - One or more arguments are invalid
FAILURE_BUCKET_ID:  STATUS_BREAKPOINT_80000003_python38.dll!PyUnicode_Concat
BUCKET_ID:  APPLICATION_FAULT_STATUS_BREAKPOINT_python38!PyUnicode_Concat+d06
ANALYSIS_SOURCE:  UM
FAILURE_ID_HASH_STRING:  um:status_breakpoint_80000003_python38.dll!pyunicode_concat

I'll edit this post if i found the reason of those python errors

**Comment by spacewaffles309** [comment]
If you stop, restart and try to re-view the manager does it get anywhere?  I've basically boiled down my .ps1 file to be this, so in case of any freezes or hiccups, this tends to push through just about everything (so far) and come back with a working view.

`cd C:\_Scripts\_python\swar\venv\Scripts; .\activate; cd ..\..; python manager.py stop; python manager.py start; python manager.py view`

**Comment by swar** [comment]
@Toasterme You can change log_level from DEBUG to INFO and it will spit out a lot of information inside of the manager.log file. What error are you getting from teh view?

**Comment by Toasterme** [comment]
> @Toasterme You can change log_level from DEBUG to INFO and it will spit out a lot of information inside of the manager.log file. What error are you getting from teh view?

i've change from ERROR to INFO in the config + restart the manager... the log is still at 0k ?!

  check_interval: 60
  log_level: INFO

![image](https://user-images.githubusercontent.com/732881/116828924-c208ac80-ab6f-11eb-98d1-327c7e68ad46.png)

**Comment by swar** [comment]
I am going to assume this is working? If not please reopen the ticket
