### ISSUE TITLE
Exclude final directory

### ISSUE THREAD

**Issue by justmemo** [swar/Swar-Chia-Plot-Manager#639]
Thanks for to the chia plot manager, I have a question. I'm using the pool system from hpool. And you know if you want to use hpool you cannot join solo farming. I was selected for the new plot  `Exclude final directory`. How can I do something with swar chia plot manager? Because swar chia plot manager added to the disk on chia mainnet every after plotting
**Screenshot**
![Capture](https://user-images.githubusercontent.com/84389361/119005795-9eea4500-b944-11eb-820f-5001f26a05c7.PNG)

**Comment by vikar123** [comment]
v.0.1.0 has this option. Download it :)

**Comment by justmemo** [comment]
I didn't realize !! I'm gonna download right now thank you :)
