### ISSUE TITLE
Please help to install SWAR on Macbook 

### ISSUE THREAD

**Issue by luisfgbb** [swar/Swar-Chia-Plot-Manager#642]
Hi guys, how are you? I'm trying to follow the tutorial to install SWAR on Mac but I can't find anything on the network. x which leading to Windows similarity does not allow me to continue. : /
Any tutorial on how to install SWAR on MAC?
Thanks in advance.
I get stuck in the section pip install -r requirements.txt
the code does not accept me

MacBook-Pro-de-fraga-2:~ fraga$ cd /Users/fraga/Documents/swar 
MacBook-Pro-de-fraga-2:swar fraga$ python3
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 **>>> pip install -r requirements.txt
  File "<stdin>", line 1
    pip install -r requirements.txt
        ^
SyntaxError: invalid syntax
>>>**

**Comment by asukahan** [comment]
> Hi guys, how are you? I'm trying to follow the tutorial to install SWAR on Mac but I can't find anything on the network. x which leading to Windows similarity does not allow me to continue. : /
> Any tutorial on how to install SWAR on MAC?
> Thanks in advance.
> I get stuck in the section pip install -r requirements.txt
> the code does not accept me
> 
> MacBook-Pro-de-fraga-2:~ fraga$ cd /Users/fraga/Documents/swar
> MacBook-Pro-de-fraga-2:swar fraga$ python3
> Python 3.9.5 (v3.9.5:0a7dcbdb13, May 3 2021, 13:17:02)
> [Clang 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> **>>> pip install -r requirements.txt
> File "", line 1
> pip install -r requirements.txt
> ^
> SyntaxError: invalid syntax
> 
> > > > **

pip3 install -r requirements.txt

**Comment by luisfgbb** [comment]
> > Hi guys, how are you? I'm trying to follow the tutorial to install SWAR on Mac but I can't find anything on the network. x which leading to Windows similarity does not allow me to continue. : /
> > Any tutorial on how to install SWAR on MAC?
> > Thanks in advance.
> > I get stuck in the section pip install -r requirements.txt
> > the code does not accept me
> > MacBook-Pro-de-fraga-2:~ fraga$ cd /Users/fraga/Documents/swar
> > MacBook-Pro-de-fraga-2:swar fraga$ python3
> > Python 3.9.5 (v3.9.5:0a7dcbdb13, May 3 2021, 13:17:02)
> > [Clang 6.0 (clang-600.0.57)] on darwin
> > Type "help", "copyright", "credits" or "license" for more information.
> > **>>> pip install -r requirements.txt
> > File "", line 1
> > pip install -r requirements.txt
> > ^
> > SyntaxError: invalid syntax
> > > > > **
> 
> pip3 install -r requirements.txt

Done tkx :)
