### ISSUE TITLE
Chat ID for telegram notifications

### ISSUE THREAD

**Issue by Orayi** [swar/Swar-Chia-Plot-Manager#646]
Unless I'm missing something there doesn't seem to be an option in the config to add the chat_id required by the telegram notifier for it to work.

When you set notify_telegram to true it throws an error when starting the manager that the chat id is missing.

**Comment by alx741** [comment]
Cross reference to discussion #634 

Make sure to surround your token with singles quotes like (replace with the token you've got from bot_father):

```yaml
  notify_telegram: true
  telegram_token: '688*****888:AA****nbJW5p*****40T21******v7I*****E'
```

Then, **before** starting the manager, send a Telegram message to your bot, you can do that by searching for it with the name you gave it, then send any message to it ("hi" is fine). Now you can start the manager `$ python manager.py start` and it should work.

**Comment by Orayi** [comment]
Thanks, Daniel. Got it to work with a new bot with those instructions.
