### ISSUE TITLE
Skip_full_destinations: True - erros when they are network drives

### ISSUE THREAD

**Issue by Ron-ski** [swar/Swar-Chia-Plot-Manager#656]
I downloaded the latest version (v0.1.0b) tonight and had a few errors, some of my own making. But Skip_full_destinations: True fails (stops the manager starting) when specified in the UNC format such as \\\server\Completed plots 1

I believe it fails because it can't get the size/free space on the drive. Perhaps it will work if I map the drive to a drive letter, but I thought I read someone had issues with mapped drives???

From the CMD window:

(venv) C:\Users\ChiaMining\Swar-Chia-Plot-Manager-main>python manager.py start
Traceback (most recent call last):
  File "C:\Users\ChiaMining\Swar-Chia-Plot-Manager-main\manager.py", line 30, in <module>
    start_manager()
  File "C:\Users\ChiaMining\Swar-Chia-Plot-Manager-main\plotmanager\library\utilities\commands.py", line 55, in start_manager
    raise ManagerError('Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.')
plotmanager.library.utilities.exceptions.ManagerError: Failed to start Manager. Please look at debug.log for more details on the error. It is in the same folder as manager.py.

Setting Skip_full_destinations: False solved the problem, but it would have been a nice feature to have.

[debug.log](https://github.com/swar/Swar-Chia-Plot-Manager/files/6518953/debug.log)

**Comment by YetNeleven** [comment]
Hi, i get the same problem too.. help me please to slve this.. wthat's going wrong?

**Comment by tritechnik** [comment]
Same issue:
```
2021-05-20 22:27:25 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\swar\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\swar\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\swar\stateless-manager.py", line 104, in <module>
    system_drives=system_drives,
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 262, in monitor_jobs_to_start
    drives_free_space=drives_free_space,
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\swar\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
TypeError: 'in <string>' requires string as left operand, not NoneType

```

**Comment by cjackson234** [comment]
@tritechnik, as the op stated, set "skip_full_destinations" will get it running again. Based on your use case though, I think you wanted that feature, right?

**Comment by Ron-ski** [comment]
I didn't have the time to check last night, but providing mapped network drives work within Swar/chia I think that will enable this feature to be used.

My reasoning is that if I navigate to my sever via network in explorer, right click a shared folder it doesn't report the used size/free space, however if I map the share to a drive letter it does.

Obviously this needs a little bit of juggling in the settings to test.

Perhaps the author could pop up a warning when starting the manager, and then turn off the feature if UNC paths are in use, so it doesn't crash out.

PS Great work, and thank you.

**Comment by GAMEBOOK** [comment]
I have exactly same error but I don't have any \\DRIVE on network (on config.yaml).
Tryed to disable (false) Skip_full_destinations but same problem.
Any idea ?

**Comment by runechronos** [comment]
@Ron-ski I tried both ways, it does not work. I noticed as u said if i share the disk, i can see the remaning space in the explorer, and if i just share a folder i can't see it. But even if you share your drive lets say "**drive1**". And that you create a folder "**folder1**" inside it.
Then you access your network with **\\mynetwork\disk1\folder1** the error remains and swar-chia is not yet capable of seeing the available space of the hard drive. It does require, i think, a fix by the author on the next minor release !

Thanks in advance for your help. For now i'll let this setting on off.

**Comment by Ron-ski** [comment]
@runechronos it's not clear if you mapped the shared folder to a drive letter, did you try mapping it to a drive letter?

**Comment by runechronos** [comment]
@Ron-ski  yes i did the "**disk1**" i wrote above is correspionding to a "drive letter in my case

**Comment by tritechnik** [comment]
> I didn't have the time to check last night, but providing mapped network drives work within Swar/chia I think that will enable this feature to be used.

Unless this changed in the new release, mapped drive letters do not work. UNC paths worked fine in prior releases for a single drive, never tested with multiples. 

Unfortunately having multiple drives without the free space check kinda kills that feature for me.

**Comment by hackhy** [comment]
you may modify this file to solve that:  

plotmanager/library/utilities/jobs.py
line 55：if drives_free_space[drive] is None or drives_free_space[drive] >= job_size:

**Comment by Ron-ski** [comment]
My PC crashed tonight, so I updated Windows and Chia, mapped my network drive, changed the config to suit and set skip_full_destinations: true and it seems to be working perfectly, see attached.

So mapped drives do work, and thus the free space feature can be used.

[ManagerView.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6525253/ManagerView.txt)

**Comment by tritechnik** [comment]
> you may modify this file to solve that:
> 
> plotmanager/library/utilities/jobs.py
> line 55：if drives_free_space[drive] is None or drives_free_space[drive] >= job_size:
> 
> change to
> 
> if (1==1):

This didn't work for me:

```
TypeError: 'in <string>' requires string as left operand, not NoneType
2021-05-22 20:11:28 [ERROR]: Failed to get disk_usage of drive None.
Traceback (most recent call last):
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File "C:\swar\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File "C:\swar\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError: argument 1 must be str, not None
Traceback (most recent call last):
  File "C:\swar\stateless-manager.py", line 104, in <module>
    system_drives=system_drives,
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 262, in monitor_jobs_to_start
    drives_free_space=drives_free_space,
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 284, in start_work
    get_target_directories(job, drives_free_space=drives_free_space)
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
    job = check_valid_destinations(job, drives_free_space)
  File "C:\swar\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
    drive = identify_drive(file_path=directory, drives=drives)
  File "C:\swar\plotmanager\library\utilities\processes.py", line 136, in identify_drive
    if drive not in file_path:
```

**Comment by hackhy** [comment]
> > you may modify this file to solve that:
> > plotmanager/library/utilities/jobs.py
> > line 55：if drives_free_space[drive] is None or drives_free_space[drive] >= job_size:
> > change to
> > if (1==1):
> 
> This didn't work for me:
> 
> ```
> TypeError: 'in <string>' requires string as left operand, not NoneType
> 2021-05-22 20:11:28 [ERROR]: Failed to get disk_usage of drive None.
> Traceback (most recent call last):
>   File "C:\swar\plotmanager\library\utilities\jobs.py", line 173, in monitor_jobs_to_start
>     free_space = psutil.disk_usage(drive).free
>   File "C:\swar\venv\lib\site-packages\psutil\__init__.py", line 1995, in disk_usage
>     return _psplatform.disk_usage(path)
>   File "C:\swar\venv\lib\site-packages\psutil\_pswindows.py", line 265, in disk_usage
>     total, free = cext.disk_usage(path)
> TypeError: argument 1 must be str, not None
> Traceback (most recent call last):
>   File "C:\swar\stateless-manager.py", line 104, in <module>
>     system_drives=system_drives,
>   File "C:\swar\plotmanager\library\utilities\jobs.py", line 262, in monitor_jobs_to_start
>     drives_free_space=drives_free_space,
>   File "C:\swar\plotmanager\library\utilities\jobs.py", line 284, in start_work
>     get_target_directories(job, drives_free_space=drives_free_space)
>   File "C:\swar\plotmanager\library\utilities\jobs.py", line 26, in get_target_directories
>     job = check_valid_destinations(job, drives_free_space)
>   File "C:\swar\plotmanager\library\utilities\jobs.py", line 53, in check_valid_destinations
>     drive = identify_drive(file_path=directory, drives=drives)
>   File "C:\swar\plotmanager\library\utilities\processes.py", line 136, in identify_drive
>     if drive not in file_path:
> ```

my solution just for Skip_full_destinations parameters.
You may change swar-chia-plot-manager's config.yaml
log_level: ERROR   ---->  log_level: INFO

than see the debug.log for more information.

**Comment by Ron-ski** [comment]
It would appear that mapped drive letters are case sensitive, and need to be upper case. I've not confirms this though.

**Comment by nlitz88** [comment]
Just wanted to make a quick note: I encountered this, but it was because I hadn't removed one of the default jobs found in my config.yaml file. Once I removed the lines for the provided jobs, it started as expected.

**Comment by Zoervleisj** [comment]
> It would appear that mapped drive letters are case sensitive, and need to be upper case. I've not confirmed this though.

Can confirm, fixed my problem
