### ISSUE TITLE
Cant seem to get jobs to start

### ISSUE THREAD

**Issue by WernerVoss** [swar/Swar-Chia-Plot-Manager#66]
not sure what Im doing wrong, Ive got the manager running and it shows jobs I start through the GUI but the manager doesnt seem to be starting new jobs.

  - name: M2-1
    max_plots: 999
    farmer_public_key: .....
    pool_public_key:
    temporary_directory: A:\
    temporary2_directory: 
    destination_directory: D:\Plots
    size: 32
    bitfield: true
    threads: 30
    buckets: 128
    memory_buffer: 5000
    max_concurrent: 3
    max_concurrent_with_start_early: 6
    stagger_minutes: 5
    max_for_phase_1: 3
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false

Tried letting it run twice so far with no results.

**Comment by Amneamnius** [comment]
Check the logs for any errors? You can also try changing the log_level: ERROR to INFO in the yalm file to see if it gives more information. Maybe try A:\ instead of just A:?

**Comment by WernerVoss** [comment]
ill switch the logs and give it a shot, so far no errors are there (I probably should have mentioned that) and ill give A:\ a try

**Comment by WernerVoss** [comment]
> 
> 
> Check the logs for any errors? You can also try changing the log_level: ERROR to INFO in the yalm file to see if it gives more information. Maybe try A:\ instead of just A:?

looks like its already A:\ im not sure how it got lost in the post

Should this start plotting when I start running SWAR? or should it only start plotting after a manually setup plot hits phase 4?

**Comment by Amneamnius** [comment]
If you run "manager.py" start it should say its starting. Then do "manager.py view" and it should show any jobs from the GUI, once those are at phase4 it should start up to 3 (since you have 6 for start early and 3 in phase1)

**Comment by WernerVoss** [comment]
> 
> 
> If you run "manager.py" start it should say its starting. Then do "manager.py view" and it should show any jobs from the GUI, once those are at phase4 it should start up to 3 (since you have 6 for start early and 3 in phase1)

that's what I figured it would do, ill have to wait and see what the logs show from attempt no 3

also thank you for the help

**Comment by WernerVoss** [comment]
all any of the logs say so far is _Second instance. Quitting._

**Comment by Amneamnius** [comment]
I'm not sure on this one, maybe try "manager.py restart"? it could already be running and you are trying to start it again.

**Comment by WernerVoss** [comment]
no dice on the restart, and ive taken a peek at open processes but I cant find anything thats obviously this running twice

**Comment by Amneamnius** [comment]
Do you have chia.exes running. Maybe wait for those to finish and restart then try starting manager again. I don't see any other info for that error

**Comment by WernerVoss** [comment]
only the one that launched when I started the manager, apparently im not the only one with the issue, found a guy on reddit

**Comment by swar** [comment]
@WernerVoss can you change your log_level from DEBUG to INFO and then send over the manager.log after it's been running for some time?

**Comment by craigbennett1981** [comment]
I had a similar issue make sure you are point to the correct chia.exe if you are using windows the path should be in the form ~\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe

**Comment by gntz555** [comment]
Also it doesn't appear in the GUI for me, BUT in the manager view and the finished plots are getting detected by the GUI. Could it be that the GUI didn't detect your final plot directory? Try to add that manually here.
![image](https://user-images.githubusercontent.com/83549410/116873222-98a35b80-ac17-11eb-9e2b-9952ede493b9.png)

**Comment by WernerVoss** [comment]
I found it last night but wanted to make sure it ran and restarted, I was pointed to the wrong exe

Thanks for the help everyone
