### ISSUE TITLE
Unsafe finalization sequence

### ISSUE THREAD

**Issue by aolkhov** [swar/Swar-Chia-Plot-Manager#666]
Great tool, helps a lot. Thank you for developing and supporting it.

Wanted to bring to your attention a little problem with the logic which cost me a fully baked plot:
After phase 4 has finished, we move the plot to its destination:
1. copy the plot file
2. remove the source file
3. rename the target file on the destination

My destination drive has disconnected while copy was in progress. Swar proceeded to step 2 removing the source, then to step 3 trying to rename the destination file, failing and "Retrying in five minutes". I've re-mounted the drive and the rename succeeded, but the source file was already gone. Should we run the rename first, it would retry, and the user would have chance to save the plot file somewhere. Also would be nice to ensure the source and destination lengths are the same before deletion.

**Comment by mauver** [comment]
that's not this script's sequence, chia's plotter sequence.

**Comment by aolkhov** [comment]
Ok, thanks for the clarification
