### ISSUE TITLE
Provide option to start manager without starting "farmer" service

### ISSUE THREAD

**Issue by beef1218** [swar/Swar-Chia-Plot-Manager#68]
Currently when the manager starts, it starts multiple chia services including both "harvester" and "farmer" services. It also adds the plot path to chia. 
In my case, I only want to launch jobs to **plot** and not **farming**. I have to manually stop the *farmer* service manually and remove the directory added by the manager.
This is a feature enhancement request.

**Comment by swar** [comment]
@beef1218  the manager does not have any functionality to start chia services such as harvester / farmer. I am not seeing how this could be happening?

**Comment by beef1218** [comment]
@swar I tested it again. Indeed the manager does not start the "farmer" service. However, it does add the "destination" directory to chia as if it executes `chia plots add -d 'SOME_PATH'`. As a result, if I have full node running, it will automatically scan the plots in the newly added destination directory and starts farming.  
Currently I have to manually remove the directory added by the manager by executing `chia plots remove -d 'SOME_PATH'`

**Comment by tooeffayy** [comment]
The plot manager is simply a wrapper around the built in Chia commands, the issue you're describing is with the Chia software itself. The chia plots create command does this from my own experience.

**Comment by garthheff** [comment]
@beef1218 You are pointing towards the GUI executable which opens all processes, and not exe you need.  e.g 

Don't use,
C:\Users\<>\AppData\Local\chia-blockchain\chia.exe

Use,
C:\Users\<>\AppData\Local\chia-blockchain\app-1.1.3\resources\app.asar.unpacked\daemon\chia.exe

**Comment by beef1218** [comment]
Thanks for the explanation guys. 
I was plotting with chia GUI app when I started to use this manager in parallel. I did not exit the GUI app because I wanted it to finish those in-the-flight plottings. I will close it once it finishes and I guess the issue will be gone.
