### ISSUE TITLE
[Feature][View] Add columns to see maximum used space

### ISSUE THREAD

**Issue by WizardPC** [swar/Swar-Chia-Plot-Manager#72]
It will be interresting to know the maximum size used.
- "max_temps_size" for plots
- "max_used" for Drive

With this, it will be easy to see if we can add more plot in parallel (if plotting drive is the limiting factor)

Eg: 1Tb Nvme SSD = 0.91TiB available, 3 plots avec OK, 4 plots it's at the limit... but with stagger perhaps it's OK ?

**Comment by swar** [comment]
I see what you're saying, but there are other tools that can accomplish this type of analysis for you that would do a much better job than what I can give to you. I think running something like that would help accomplish what you are trying to do.
