### ISSUE TITLE
chia Manager running but jobs don't start

### ISSUE THREAD

**Issue by ChiaDave** [swar/Swar-Chia-Plot-Manager#750]
I try to start the chia manager. After its running, the jobs don't start and task manager shows no action on the SSD's or CPU. What am i doing wrong? I checked the config more times, can't find any mistake.

Manager displays following: 

====================================================================================================
num   job   k   plot_id   pid   start   elapsed_time   phase   phase_times   progress   temp_size
====================================================================================================
====================================================================================================
Manager Status: Running

===============================================================
type   drive     used     total      %      #    temp   dest
===============================================================
t/-    D:      0.00TiB   0.91TiB    0.0%   -/-
t/-    E:      0.00TiB   0.91TiB    0.0%   -/-
-/d    F:      0.00TiB   14.55TiB   0.0%   -/-
-/d    G:      0.00TiB   14.55TiB   0.0%   -/-
===============================================================
CPU Usage: 13.1%
RAM Usage: 5.98/63.88GiB(9.4%)

Plots Completed Yesterday: 0
Plots Completed Today: 0

Next log check at 2021-05-22 17:44:07

[config.txt](https://github.com/swar/Swar-Chia-Plot-Manager/files/6526723/config.txt)

**Comment by ChiaDave** [comment]
![Manager Status](https://user-images.githubusercontent.com/84605974/119232642-3a86db80-bb26-11eb-8868-ebe564e8ca35.PNG)

**Comment by dzerryboberski** [comment]
i have same issue on ubuntu,
just created new system fresh system
1.1.6 and Swar 0.1
made one plot via chia cli
but it's not starting via Swar
rebooted system few times and checked config.yaml each time :(

on other system
working on 1.1.5 and Swar 0.9
i don't have any issues

**Comment by ChiaDave** [comment]
https://github.com/swar/Swar-Chia-Plot-Manager/discussions/702

solved
