### ISSUE TITLE
Failed to get disk_usage of drive None.

### ISSUE THREAD

**Issue by nabla1** [swar/Swar-Chia-Plot-Manager#770]
With the new build from two days ago. I keep getting error as below.
Z:\ is network drive. Any help is appreciated. 

2021-05-22 203540 [INFO] Monitoring jobs to start.
2021-05-22 203540 [ERROR] Failed to get disk_usage of drive None.
Traceback (most recent call last)
  File CUsersAdministratorDesktopSwar-Chia-Plot-Managerplotmanagerlibraryutilitiesjobs.py, line 173, in monitor_jobs_to_start
    free_space = psutil.disk_usage(drive).free
  File CUsersAdministratorAppDataLocalProgramsPythonPython39libsite-packagespsutil__init__.py, line 1995, in disk_usage
    return _psplatform.disk_usage(path)
  File CUsersAdministratorAppDataLocalProgramsPythonPython39libsite-packagespsutil_pswindows.py, line 265, in disk_usage
    total, free = cext.disk_usage(path)
TypeError argument 1 must be str, not None
2021-05-22 203540 [INFO] Free space before checking active jobs {'Z' 24432185053184, None None}

**Comment by helldoradono** [comment]
same here 
python 3.7 
client 1.1.6

**Comment by sblnrrk** [comment]
skip_full_destinations: false

**Comment by Ron-ski** [comment]
See https://github.com/swar/Swar-Chia-Plot-Manager/issues/656

It will not work with UNC paths as it can't get the free space, map the network drive to a drive letter instead and it works.

**Comment by jgilpin** [comment]
I found that the drive letters are case sensitive. Have you tried Z: instead of z: ?

**Comment by mleen** [comment]
the same Problem
win10/chia1.1.6/python3.7
withuot  UNC path
set :skip_full_destinations: false, Then it works.

**Comment by nabla1** [comment]
@jgilpin Thanks. Z:\ works without errors.

**Comment by mleen** [comment]
> the same Problem
> win10/chia1.1.6/python3.7
> withuot UNC path
> set :skip_full_destinations: false, Then it works.

原来盘符必须要大写。symbol of a partition Must be Capital form
