### ISSUE TITLE
[Bug] Network directories are not recognized

### ISSUE THREAD

**Issue by djdookie** [swar/Swar-Chia-Plot-Manager#80]
It seems that network directories are not recognized.

If you put e.g. \\nas\plots into config as destination_directory, it is not shown in the view.
Do we have to mask such directories somehow?

**Comment by Amneamnius** [comment]
I think this is a known issue. For now you would have to run another script to copy files out from a local drive to your NAS or mask it somehow to appear as a local drive.

**Comment by spacewaffles309** [comment]
Depending on your LAN speed, writing directly to the NAS can slow things down while the process waits for the move to finish.  I've taken the approach of moving finished plots to another folder on my high speed drives, then I have robocopy running in /mon mode (Win10) watching to move the plots later.  It's been nice for letting the manager move on to the next job a little earlier.

**Comment by swar** [comment]
What is your config.yaml looking like? Because it does recognize network directories on Windows, but not sure about Linux / Mac. I think it should as well
