### ISSUE TITLE
Restarting view due to psutil going stale...

### ISSUE THREAD

**Issue by kchang4** [swar/Swar-Chia-Plot-Manager#81]
Happens about 10 hours ish after initial run? Then it'll happen every 20-30mins ish after that.
Problem is that it doesn't actually end up restarting the view, it basically freezes the terminal

Seems like it has to do with this portion of the code

```
// commands.py
has_file = False
  if len(running_work.values()) == 0:
    has_file = True
  for work in running_work.values():
    if not work.log_file:
      continue
    has_file = True
    break
```

I can probably try running a debugging process and see which is setting it false, but do you have a hunch?

I'm on windows 10, running this through the windows terminal.  This happens regardless if I run after activating the venv or not

**Comment by tanvrkhan** [comment]
I have the same issue.

**Comment by garthheff** [comment]
i started getting this since updating to chia 1.1.3

**Comment by spacewaffles309** [comment]
I would see this pretty frequently on at least one machine (the one my eyeballs are in front of the most) but actually haven't seen, or at least noticed, it since I grabbed the newest updates.  A change in processes.py seems to have been very good for me, at least over yesterday and this morning.

**Comment by swar** [comment]
I think you should restart and try again. This issue is tied to some windows bug that some people have. View is meant to be fallible. Manager however should be resilient to errors. So if view breaks, it should still let manager run in the background.
