### ISSUE TITLE
No plots being shown

### ISSUE THREAD

**Issue by WebCoderUk** [swar/Swar-Chia-Plot-Manager#874]
Os: Windows
No plots being show in the powershell but it is plotting?

====================================================================================================
num   job   k   plot_id   pid   start   elapsed_time   phase   phase_times   progress   temp_size
====================================================================================================
====================================================================================================
Manager Status: Running

==========================================================================
 type   drive     used     total      %       #     temp   temp2   dest
==========================================================================
t/-/-   F:      0.14TiB   0.91TiB   14.8%   -/-/-
-/-/d   G:      0.00TiB   0.91TiB   0.0%    -/-/-
-/-/d   H:      1.88TiB   5.46TiB   34.5%   -/-/-
-/-/d   I:      1.39TiB   5.46TiB   25.4%   -/-/-
==========================================================================
CPU Usage: 69.4%
RAM Usage: 17.40/31.90GiB(54.5%)

**Comment by haniham** [comment]
removing the space in the windows user profile name has helped me

**Comment by WebCoderUk** [comment]
Sorted it - Ive been used to using a manager with chia2.exe changed to normal chia.exe and its showing now.
