### ISSUE TITLE
Feature request: Directory list for temp directory

### ISSUE THREAD

**Issue by Chilli71** [swar/Swar-Chia-Plot-Manager#937]
Hello,
I'm using for each plot a temp HDD, a temp2 HDD and a final RAID0.
temp2 and final do support directory lists, temp not (yet).
At the moment I work around by defining 8 jobs (later 16 jobs when the drives arrive). But features like staggering or 'not more than xy tasks in phase 1' can not be used that way.
Adding the options for multiple directories for temp would really simplify things.

Regards Chilli

**Comment by kissaev** [comment]
just do folders tempDir\01 tempDir\02 etc for each job

**Comment by Tuckie** [comment]
`temporary_directory` - Can be a single value or a list of values.

**Comment by Chilli71** [comment]
> just do folders tempDir\01 tempDir\02 etc for each job

That's what I did. But as mentioned it is does not satisfy as you can't stagger jobs, no prevent that too many jobs are at phase 1 at once.

**Comment by Chilli71** [comment]
> `temporary_directory` - Can be a single value or a list of values.

This is new! It looks like the feature was added 8 dayas ago.
This is great. Just in time befor the next 16 HDD arrive.
The devs must be very experienced clairvoyants, implementing features one week before they are requested.

Thanks for the heads up!
