### ISSUE TITLE
Viewer elapsed time incorrect if plot takes more than a day

### ISSUE THREAD

**Issue by griffithJ** [swar/Swar-Chia-Plot-Manager#95]
If a plot takes more than 24 hours (don't ask), the elapsed time shown by the viewer is rounded to the nearest day. Fix in print.py:

    diff --git a/plotmanager/library/utilities/print.py b/plotmanager/library/utilities/print.py
    index ef6cf4c..6eee756 100644
    --- a/plotmanager/library/utilities/print.py
    +++ b/plotmanager/library/utilities/print.py
    @@ -10,7 +10,7 @@ def _get_row_info(pid, running_work, view_settings):
         work = running_work[pid]
         phase_times = work.phase_times
         elapsed_time = (datetime.now() - work.datetime_start)
    -    elapsed_time = pretty_print_time(elapsed_time.seconds)
    +    elapsed_time = pretty_print_time(elapsed_time.seconds + elapsed_time.days * 86400)
         phase_time_log = []
         for i in range(1, 5):
             if phase_times.get(i):

**Comment by swar** [comment]
Any chance you can make this a pull requests so I can check it out?
