### ISSUE TITLE
options for choose actions of destination_directory

### ISSUE THREAD

**Issue by ruixingchen** [swar/Swar-Chia-Plot-Manager#96]
current code will split plot file to destination directory evenly, how about add an option to choose the action:
1, fill destination disk one by one
2, fill destination disk evenly
3, prefer the one that has most space
4, prefer the one that has most % space
I can only read python, not write 😭

**Comment by swar** [comment]
I plan on doing some of this, but if you want to learn Python in the meantime and contribute your help will be appreciated.

No date of when any of this will be implemented. I am only one person.
