### ISSUE TITLE
4 nvme but only runs 3?

### ISSUE THREAD

**Issue by daedalus1200** [swar/Swar-Chia-Plot-Manager#977]
Below are my setting and I even changed the task order from bottom to top to see if I have any grammar mistake but still just runs 3 tasks. It can find 4 devices but only runs 3. I'm running on 5950x I appreciate whoever knows the reason.

  - name: XPG 1
    max_plots: 36
    farmer_public_key:
    pool_public_key:
    temporary_directory: D:\
    temporary2_directory: C:\cache
    destination_directory: H:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 64
    memory_buffer: 8000
    max_concurrent: 7
    max_concurrent_with_start_early: 10
    initial_delay_minutes: 0
    stagger_minutes: 20
    max_for_phase_1: 7
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 0, 1, 2, 3, 4, 5, 6, 7 ]

  - name: XPG 2
    max_plots: 36
    farmer_public_key:
    pool_public_key:
    temporary_directory: E:\
    temporary2_directory: C:\cache
    destination_directory: I:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 64
    memory_buffer: 8000
    max_concurrent: 7
    max_concurrent_with_start_early: 10
    initial_delay_minutes: 5
    stagger_minutes: 20
    max_for_phase_1: 7
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 8, 9, 10, 11, 12, 13, 14, 15 ]

  - name: XPG 3
    max_plots: 36
    farmer_public_key:
    pool_public_key:
    temporary_directory: F:\
    temporary2_directory: C:\cache
    destination_directory: H:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 64
    memory_buffer: 8000
    max_concurrent: 7
    max_concurrent_with_start_early: 10
    initial_delay_minutes: 10
    stagger_minutes: 20
    max_for_phase_1: 7
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 16, 17, 18, 19, 20, 21, 22, 23 ]

  - name: XPG 4
    max_plots: 30
    farmer_public_key:
    pool_public_key:
    temporary_directory: G:\
    temporary2_directory: C:\cache
    destination_directory: I:\
    size: 32
    bitfield: true
    threads: 4
    buckets: 64
    memory_buffer: 8000
    max_concurrent: 7
    max_concurrent_with_start_early: 8
    initial_delay_minutes: 15
    stagger_minutes: 20
    max_for_phase_1: 7
    concurrency_start_early_phase: 4
    concurrency_start_early_phase_delay: 0
    temporary2_destination_sync: false
    exclude_final_directory: false
    skip_full_destinations: true
    unix_process_priority: 10
    windows_process_priority: 32
    enable_cpu_affinity: true
    cpu_affinity: [ 24, 25, 26, 27, 28, 29, 30, 31 ]

**Comment by tob-pas** [comment]
you know, there is a global parameter? (must be at line 108)
max_concurrent and max_for_phase_1
